// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AttendanceRecordStatus.
const (
	AttendanceRecordStatusAbsent  AttendanceRecordStatus = "absent"
	AttendanceRecordStatusLate    AttendanceRecordStatus = "late"
	AttendanceRecordStatusPending AttendanceRecordStatus = "pending"
	AttendanceRecordStatusPresent AttendanceRecordStatus = "present"
)

// Valid indicates whether the value is a known member of the AttendanceRecordStatus enum.
func (e AttendanceRecordStatus) Valid() bool {
	switch e {
	case AttendanceRecordStatusAbsent:
		return true
	case AttendanceRecordStatusLate:
		return true
	case AttendanceRecordStatusPending:
		return true
	case AttendanceRecordStatusPresent:
		return true
	default:
		return false
	}
}

// Defines values for DailyLogRowStatus.
const (
	DailyLogRowStatusAbsent  DailyLogRowStatus = "absent"
	DailyLogRowStatusLate    DailyLogRowStatus = "late"
	DailyLogRowStatusPending DailyLogRowStatus = "pending"
	DailyLogRowStatusPresent DailyLogRowStatus = "present"
)

// Valid indicates whether the value is a known member of the DailyLogRowStatus enum.
func (e DailyLogRowStatus) Valid() bool {
	switch e {
	case DailyLogRowStatusAbsent:
		return true
	case DailyLogRowStatusLate:
		return true
	case DailyLogRowStatusPending:
		return true
	case DailyLogRowStatusPresent:
		return true
	default:
		return false
	}
}

// Defines values for HolidaySource.
const (
	Manual    HolidaySource = "manual"
	NagerDate HolidaySource = "nager_date"
)

// Valid indicates whether the value is a known member of the HolidaySource enum.
func (e HolidaySource) Valid() bool {
	switch e {
	case Manual:
		return true
	case NagerDate:
		return true
	default:
		return false
	}
}

// Defines values for LeaveRequestStatus.
const (
	LeaveRequestStatusApproved LeaveRequestStatus = "approved"
	LeaveRequestStatusPending  LeaveRequestStatus = "pending"
	LeaveRequestStatusRejected LeaveRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the LeaveRequestStatus enum.
func (e LeaveRequestStatus) Valid() bool {
	switch e {
	case LeaveRequestStatusApproved:
		return true
	case LeaveRequestStatusPending:
		return true
	case LeaveRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ReportExportStatus.
const (
	Failed     ReportExportStatus = "failed"
	Processing ReportExportStatus = "processing"
	Ready      ReportExportStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReportExportStatus enum.
func (e ReportExportStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Processing:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	Admin       UserRole = "admin"
	Employee    UserRole = "employee"
	Supervisor  UserRole = "supervisor"
	SystemOwner UserRole = "system_owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Employee:
		return true
	case Supervisor:
		return true
	case SystemOwner:
		return true
	default:
		return false
	}
}

// AttendanceRecord defines model for AttendanceRecord.
type AttendanceRecord struct {
	AutoClosed bool `json:"auto_closed"`

	// CheckInAt Example: 09:03:00
	CheckInAt *string `json:"check_in_at,omitempty"`

	// CheckOutAt Example: 17:05:00
	CheckOutAt *string                `json:"check_out_at,omitempty"`
	EmployeeId string                 `json:"employee_id"`
	Id         string                 `json:"id"`
	Status     AttendanceRecordStatus `json:"status"`
	WorkDate   openapi_types.Date     `json:"work_date"`
}

// AttendanceRecordStatus defines model for AttendanceRecord.Status.
type AttendanceRecordStatus string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string    `json:"access_token"`
	ExpiresAt   time.Time `json:"expires_at"`
	User        User      `json:"user"`
}

// CheckInRequest defines model for CheckInRequest.
type CheckInRequest struct {
	// IdempotencyKey Client-generated, stable across retries of the same logical attempt.
	IdempotencyKey string `json:"idempotency_key"`
	QrToken        string `json:"qr_token"`
}

// CheckOutRequest defines model for CheckOutRequest.
type CheckOutRequest struct {
	IdempotencyKey string `json:"idempotency_key"`
}

// CompleteRegistrationRequest defines model for CompleteRegistrationRequest.
type CompleteRegistrationRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	StudentGen string `json:"student_gen"`
}

// CreateHolidayRequest defines model for CreateHolidayRequest.
type CreateHolidayRequest struct {
	Date      openapi_types.Date `json:"date"`
	LocalName *string            `json:"local_name,omitempty"`
	Name      string             `json:"name"`
}

// CreateKioskDeviceRequest defines model for CreateKioskDeviceRequest.
type CreateKioskDeviceRequest struct {
	Name string `json:"name"`
}

// CreateLeaveRequestRequest defines model for CreateLeaveRequestRequest.
type CreateLeaveRequestRequest struct {
	EndDate openapi_types.Date `json:"end_date"`

	// LeaveType Free-text leave category (ประเภทการลา), distinct from reason.
	LeaveType *string            `json:"leave_type,omitempty"`
	Reason    *string            `json:"reason,omitempty"`
	StartDate openapi_types.Date `json:"start_date"`
}

// DailyLogRow defines model for DailyLogRow.
type DailyLogRow struct {
	AutoClosed bool               `json:"auto_closed"`
	CheckInAt  *string            `json:"check_in_at,omitempty"`
	CheckOutAt *string            `json:"check_out_at,omitempty"`
	Date       openapi_types.Date `json:"date"`
	EmployeeId string             `json:"employee_id"`
	FirstName  *string            `json:"first_name,omitempty"`
	LastName   *string            `json:"last_name,omitempty"`
	Status     DailyLogRowStatus  `json:"status"`
}

// DailyLogRowStatus defines model for DailyLogRow.Status.
type DailyLogRowStatus string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Holiday defines model for Holiday.
type Holiday struct {
	Date      openapi_types.Date `json:"date"`
	Id        string             `json:"id"`
	LocalName *string            `json:"local_name,omitempty"`
	Name      string             `json:"name"`
	Source    HolidaySource      `json:"source"`
}

// HolidaySource defines model for Holiday.Source.
type HolidaySource string

// KioskDevice defines model for KioskDevice.
type KioskDevice struct {
	CreatedBy *string `json:"created_by,omitempty"`
	DeviceId  string  `json:"device_id"`
	Id        string  `json:"id"`

	// MaskedToken Example: ••••••••ab12
	MaskedToken string `json:"masked_token"`
	Name        string `json:"name"`
}

// KioskDeviceWithToken defines model for KioskDeviceWithToken.
type KioskDeviceWithToken struct {
	CreatedBy *string `json:"created_by,omitempty"`
	DeviceId  string  `json:"device_id"`
	Id        string  `json:"id"`

	// MaskedToken Example: ••••••••ab12
	MaskedToken string `json:"masked_token"`
	Name        string `json:"name"`

	// Token The full raw device token. Only ever returned here and from rotate.
	Token string `json:"token"`
}

// LeaveRequest defines model for LeaveRequest.
type LeaveRequest struct {
	CreatedAt  time.Time          `json:"created_at"`
	DecidedAt  *time.Time         `json:"decided_at,omitempty"`
	DecidedBy  *string            `json:"decided_by,omitempty"`
	EmployeeId string             `json:"employee_id"`
	EndDate    openapi_types.Date `json:"end_date"`
	Id         string             `json:"id"`
	LeaveType  *string            `json:"leave_type,omitempty"`
	Reason     *string            `json:"reason,omitempty"`
	StartDate  openapi_types.Date `json:"start_date"`
	Status     LeaveRequestStatus `json:"status"`
}

// LeaveRequestStatus defines model for LeaveRequest.Status.
type LeaveRequestStatus string

// LineAuthorizeResponse defines model for LineAuthorizeResponse.
type LineAuthorizeResponse struct {
	AuthorizeUrl string `json:"authorize_url"`
}

// LineLoginRequest defines model for LineLoginRequest.
type LineLoginRequest struct {
	Code        string `json:"code"`
	RedirectUri string `json:"redirect_uri"`

	// State Must equal the state returned by /auth/line/authorize.
	State string `json:"state"`
}

// MonthlyReportRow defines model for MonthlyReportRow.
type MonthlyReportRow struct {
	AbsentCount int     `json:"absent_count"`
	EmployeeId  string  `json:"employee_id"`
	FirstName   *string `json:"first_name,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	LateCount   int     `json:"late_count"`
	LateMinutes int     `json:"late_minutes"`
	LeaveDays   int     `json:"leave_days"`
	WorkDays    int     `json:"work_days"`

	// WorkedHours Capped to each day's scheduled shift length — never counts time outside the scheduled window, even with a real late checkout.
	WorkedHours float32 `json:"worked_hours"`
}

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// QRTokenResponse defines model for QRTokenResponse.
type QRTokenResponse struct {
	ExpiresAt time.Time `json:"expires_at"`
	Token     string    `json:"token"`
}

// ReplaceScheduleRequest defines model for ReplaceScheduleRequest.
type ReplaceScheduleRequest struct {
	Rows []ReplaceScheduleRow `json:"rows"`
}

// ReplaceScheduleRow defines model for ReplaceScheduleRow.
type ReplaceScheduleRow struct {
	DayOfWeek     int                 `json:"day_of_week"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to,omitempty"`

	// EndTime Example: 17:00:00
	EndTime string `json:"end_time"`

	// StartTime Example: 09:00:00
	StartTime string `json:"start_time"`
}

// ReportExport defines model for ReportExport.
type ReportExport struct {
	Error  *string            `json:"error,omitempty"`
	Id     string             `json:"id"`
	Month  string             `json:"month"`
	Status ReportExportStatus `json:"status"`
}

// ReportExportStatus defines model for ReportExport.Status.
type ReportExportStatus string

// RequestExportRequest defines model for RequestExportRequest.
type RequestExportRequest struct {
	Month string `json:"month"`
}

// UpdateHolidayRequest defines model for UpdateHolidayRequest.
type UpdateHolidayRequest struct {
	LocalName *string `json:"local_name,omitempty"`
	Name      string  `json:"name"`
}

// User defines model for User.
type User struct {
	DisplayName  *string  `json:"display_name,omitempty"`
	FirstName    *string  `json:"first_name,omitempty"`
	Id           string   `json:"id"`
	IsRegistered bool     `json:"is_registered"`
	LastName     *string  `json:"last_name,omitempty"`
	PictureUrl   *string  `json:"picture_url,omitempty"`
	Role         UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// WorkSchedule defines model for WorkSchedule.
type WorkSchedule struct {
	// DayOfWeek 0 = Sunday
	DayOfWeek     int                 `json:"day_of_week"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to,omitempty"`
	EmployeeId    string              `json:"employee_id"`

	// EndTime Example: 17:00:00
	EndTime string `json:"end_time"`
	Id      string `json:"id"`

	// StartTime Example: 09:00:00
	StartTime string `json:"start_time"`
}

// DeviceId defines model for DeviceId.
type DeviceId = string

// EmployeeId defines model for EmployeeId.
type EmployeeId = string

// ExportId defines model for ExportId.
type ExportId = string

// HolidayId defines model for HolidayId.
type HolidayId = string

// LeaveRequestId defines model for LeaveRequestId.
type LeaveRequestId = string

// Month Example: 2026-03
type Month = string

// LineAuthorizeParams defines parameters for LineAuthorize.
type LineAuthorizeParams struct {
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`
}

// ListHolidaysParams defines parameters for ListHolidays.
type ListHolidaysParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// GetKioskQRTokenParams defines parameters for GetKioskQRToken.
type GetKioskQRTokenParams struct {
	Token string `form:"token" json:"token"`
}

// GetDailyLogParams defines parameters for GetDailyLog.
type GetDailyLogParams struct {
	Month      Month   `form:"month" json:"month"`
	EmployeeId *string `form:"employee_id,omitempty" json:"employee_id,omitempty"`
}

// GetMonthlyReportParams defines parameters for GetMonthlyReport.
type GetMonthlyReportParams struct {
	Month Month `form:"month" json:"month"`
}

// CheckInJSONRequestBody defines body for CheckIn for application/json ContentType.
type CheckInJSONRequestBody = CheckInRequest

// CheckOutJSONRequestBody defines body for CheckOut for application/json ContentType.
type CheckOutJSONRequestBody = CheckOutRequest

// LineLoginJSONRequestBody defines body for LineLogin for application/json ContentType.
type LineLoginJSONRequestBody = LineLoginRequest

// PasswordLoginJSONRequestBody defines body for PasswordLogin for application/json ContentType.
type PasswordLoginJSONRequestBody = PasswordLoginRequest

// CompleteRegistrationJSONRequestBody defines body for CompleteRegistration for application/json ContentType.
type CompleteRegistrationJSONRequestBody = CompleteRegistrationRequest

// CreateHolidayJSONRequestBody defines body for CreateHoliday for application/json ContentType.
type CreateHolidayJSONRequestBody = CreateHolidayRequest

// UpdateHolidayJSONRequestBody defines body for UpdateHoliday for application/json ContentType.
type UpdateHolidayJSONRequestBody = UpdateHolidayRequest

// CreateKioskDeviceJSONRequestBody defines body for CreateKioskDevice for application/json ContentType.
type CreateKioskDeviceJSONRequestBody = CreateKioskDeviceRequest

// CreateLeaveRequestJSONRequestBody defines body for CreateLeaveRequest for application/json ContentType.
type CreateLeaveRequestJSONRequestBody = CreateLeaveRequestRequest

// RequestReportExportJSONRequestBody defines body for RequestReportExport for application/json ContentType.
type RequestReportExportJSONRequestBody = RequestExportRequest

// ReplaceEmployeeScheduleJSONRequestBody defines body for ReplaceEmployeeSchedule for application/json ContentType.
type ReplaceEmployeeScheduleJSONRequestBody = ReplaceScheduleRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3djhy3lf+rHNQ/gCWkP0Zykn8ywF7ItmzPRpbkkWRf2NoGu3i6mxkWWSJZ09MRBvDuMwTYi71ZZLH3",
	"i1wpbzPIkyx4yKqu6q7qrh7NjKVkgQDydLFYh4e/833IvE1SneVaoXI2OX6b5MywDB0a+usLPBcpnnD/",
	"30Ilx0nO3CIZJIplmBwnvHw8SAy+KYRBnhw7U+AgsekCM+bfc6vcj7XOCDVPLi8HyeMsl3qF3fPiesCB",
	"M1/k2rjOecWh832tpeBsdXMTPkF2jqf4pkB7g2R+o5VbVJO9KdCs1rNl9HDXhHjBslz6sQ+PHv5mePRp",
	"MvAUOTR+un/58Uf+9leXQ//Pw8tfJIMtAi7LyQgzj5xDxZlK8RRTbWiRudE5GieQRrDC6UkqtUVeW89U",
	"a4lMJZeDJF1gejYRasJck76j3x0ffXp8dORXV0jJpv7XsJwNospJdOG2Znnw/4+Pft1zlhKKE8FbeD9I",
	"On62jrmCFouqyJLjH5IcFfcPB0lu0KJyySCRzGEySNiU/n7d8vmlNmcT7ocdv01m2mR+LQkP720DYb3H",
	"PwQU1cmvz1ZROGjsxpoEPf0Dps6T8Khwi1O0uVYWW/YyTdHaidNnqFo5gRe5MGjjJjSWMHQia1nHICks",
	"Gj/6FwZnyXHy/8ZrHTWOSBu/8mM219ygpvHtOGnbAj/3QDlRUSq3lyg4Zrl2qNLV5AxX/ieONjUid0J7",
	"CflcClRuOEeFhjnkA7DOgwpYarS1YNAZgRb0DNwCwbIMQeq5SJkEL2ZZ7kZtbHhjOvm6se5q5GCL2s4V",
	"PyvcIUveB7YeX9Ve/hye4lxYZ5jnXicFM2GsmwQV1oIqyXY9ta7gqNxk3od3tS/V523O0roeg8xhNBGd",
	"C+kpvINE6pTJ7jV1PNhYTJycBnfT/Huh7Vmw7Z109/veng/VzV3nl1DxSX8u+Rkn4edNOfzSIA4dXjig",
	"UZAyh3NtVnDv6t1/XL37r6t3/3P115+u3v3n1bt/v3r3r1fv/kI//vfVu7/cHwAX1gmVOpgZnYFBZrVq",
	"FcvwqEvtG3dNfV17d7DmSRtvv2BCrp7o+alevr9xPdiO7n2h917us61NHbD3uw2dsHf0zVjodvFrWt3e",
	"lvZrZNItXlSENTe2RnDlyeizPrDyr7V+L6iu99BZHRvXVGV7t6Jbj+vCpFjfI8XmaEohyZgqmNy/K7QL",
	"dc1YzdzGlZpy3OZMSmqNT6arfqJA0xzoO2bMniFfm/71dv/tpz+3/o9NHzxMBte1GYE9FaUVjxp07OHU",
	"98ItXpYEMymfzZLjH3Y7cHU+Xw42GV2tvqniXy4QZoWUYNgSAs1AQ0fwTMkV4Dka728VRiGHBRoEpnhU",
	"6doxh6O9EtO14Ncb8Vs3Og7xdTmmgu9+pwfMwhw9UblP7x5kkLtUQMNO7yVpbVP7KO7+Nna3nmd5bvQ5",
	"hnDbb3JDMfePq9pNd03z14DRJkhPhEIfZmkj/og7Yq1yyKQwcr9cN4d3ffeJnotuNzzVvF01G+TCYOom",
	"hRGdEXCLj/ZNYR3gm4LJEAv5UWuBna5g7MkeS6FwXC1gv8wSnRtUlTS0rZwyJnJ1irk2rt2PIpM/SXWh",
	"XG2BQjmc+8jzZ3ZfvGOyizh6nglVuKhPt0eQhHK26ngekwW7HiOfLHQRUoUbITHLc+TgNCBLF8DZ6hML",
	"XvPzQiIHuxAz76WruVvA3376EyhS3LQeC17tgS6cFRwDSqoXl0JxvRx4Pa9gKdwCmHfVJfj1ArmqunCj",
	"H9UaMarIpi2pgtbMyMomDdZu8HHQREWDhxscaQPdc2btUhu+W+TyOKqh3aofO7Il/Sx9NXKwnrCN0G9P",
	"yZZ3a6LrJHV6pjJacjdtJJ5iLlmKLyIyOrlp9DJkNBxmdl9OaXNSvSTCw7eZMWy1RS7N34fANh3D2Wqi",
	"Z5Ml4pn/M2MXIvM26jeDJBMq/PfRoE31zGaYOnGOE+/Z9Au2qlecbnthv9eg+IT2diuXehRyqR2Wevud",
	"o991vbMVTq3505iuRs0WMzo2QxsXqgMtaDZGm15at8tjL/PvfbwPo1O0NjggBhlfJYNkxoTs7XuUCf0d",
	"kV0Uh7DgTtmoyD4k2d8kKEzRRsKrnPfIjt1I0qszCfUq5pE3pE7YXLJVf1t7oCHvivbsxFDmE01XauYw",
	"FyAXqStM5Qzu97G1bMTSdmUdZhO9VGi8aeOZ8IrXFjmac2G1qfm5PaFJn9hcatvOfK/NWaka9+rFpmtx",
	"BP8ELwrF2Ypi1A9aZfYItA5Tqd3lpvfTtC1BzQ0pX08dpoURbuU3PAs7PEVm0PiYZ/3XlyV7//n7l0ks",
	"KZKA0NP1EhbO5aHqKNRMbwOkLC9TbSVUIuHR8xOYaQNU+eCIcPXXf7t696erd38GH3o8P302gpcLYcHm",
	"mIKwwe1cMIMcUq2cYamDKboloqJnX2mYsvQMFacEg/+pqv/AzGjlPw0pVYbIw7WIwNGKuRpl4Z3Pnz19",
	"eXry2auXJ0+/8r95+nKjPduGS+/6plqdo/KrstGjFY62tVrFo+cnySA5R2OjbIwejI48IHSOiuUiOU4+",
	"HR2NYkF3Qawfr9kyJod5KMgty3VQ0F4QqTZzwstPnahYP0brPtN8FSJDv0R6g+W5FCm9M/5DDOPX1eVd",
	"DtdG6e2yCUsvVfRDcEOJ+odHRzf29a1KNX1/I5CJHAJDQ5B77v4qELER2Qqy6lDW4kAb2CyL0bsPOt8d",
	"C3XOpOAQ6pghszXwE3l8VRMLC3HgOHjJfBxTYUIxEsbwod9tf+jbU/ChMjBJrgcUFjl9oPyBEIEchAKn",
	"eXR4SwGmnF5ddH94ffnaW4wsY2aVHCffoRGzFTCwKVM+oP/2FHK2kppxuOexz7zFGgCRvRqAX7TEYWHx",
	"PolEYDKttoTmAPzOFc6z1v+u9HBuWIrDHI3QnAK/cQjLIHhEwOZMKOtoeKnTauEnCRotzkuVX9+2SOjC",
	"7ZGJZ4W7TaGoVWc/WKnQhesvFgeKAklPizR0IvupdlvgbUW2p/oa0H4umVAg1JDleZVoCLkLDd+eDvw/",
	"KcvQMLAO8wHkGMR2JvUSCvKGwS2YZxlFhgHm2oi5UEyup4xGooLmdjrML36OLcBs5BFJ56+buX5o7w7a",
	"yJj17zp6fYsQbM+HtuCwHEQfgVenT0BYW6BXNuhszC56xaK09wJSrc8E2vt7wdrgCsGkwsFnOBcKGDw5",
	"efqYujjUCL4Ryllg8PmL0y9rH2UKRKyfBAIGMBWKk3ORgdNgF9q4oRTnyMF7NVTCiEQOokL07klwR+iL",
	"bGvFTlfk0rDCeuBp78+U+VVhAdOFRk4+CzBPK+EAKoSADn5NyqQMgxSHrLDe6wFSrk7Xc7Nh5dsgpd+7",
	"VWeVcb4l3bmV0b5r5VlvlmoBLNEGtkhTRI58BC88Tplab7/BmUG7GAbYBDDAPZvqmE8lXt/3Ko5xLggF",
	"TtPWlYuCqebBtHWoWAKSdwPGudEzIRHwIl0wNUeIiQh689PtNx+llPn0gOJIrob3dzck5HE5WRSSsOYm",
	"cMkJ8XaYgUVL3msNSLsx1Eij3hKOWlO1//BY2qExy9Syt7hVbrkLgCfRsHe/dF3svYozjsvpgooOLp/X",
	"h7WcBxgtkSw4GWJimP+FjDTXaNUnzpPYUPWRCgvMeOZoZ50JtQ5duKGeDadecd7z0V6MD8dpxscWkdNH",
	"7w/81wzpZKXBm/oiB1Q810K5DYWq5zv90Cfh+RYEf9Ui8no+DzRuMOwUz/VZqLKkhTFe0UfUBH8LLJpz",
	"NEMrONZIy7qdkK/QfYPJLcpF7Pzcdkoj/dToeW338hCf8CsMJtezxAfqKUX/RdmZGlgV2dm9jadhwMtY",
	"+Hgvvt16c27vhtuWTNDWjj3FZYP70Xvbt3mDcuvIv48hcBO2myin1o+o2Vp0YrBEaoOcxiaGdOaOoLCl",
	"u/W2AsQdjbR3bKO6ZLFOGgXwnl7ew+8OhMNMoOT2bqS4ZCdQnn8Yqs9qqpnh/hul6egS8gV17f1xlz4M",
	"jX23qRMbrYMt+/ECTUgQWSjyDeF4Is5Red5RCBoXFeo2dkeoad3X5aBekSblh3dFmHvbZdvndfq9Zn3f",
	"OLZXYbnstNyuJm/tVMlU75UZ70Z7JcfRhO4YWsQ+KapJhWf62Om7ESSPCVjU6GdEb1jGCE6RcToWMV0B",
	"U6sWgRpRWatdvdab7W9Lr7Y19PdSqA9uTpBLpHQiA2Iz2aHKtL7HaxhdNwP3aVvPj5RogmPrgMqJ43Ux",
	"cdwoNx6Eq0ecA4PQ7StXQ1RUVyyR1lRY47eCXwbavE7fBtIX9PsaSBuaq21v1kPG6wOBLYqjxe8u9yxQ",
	"wz8engc2ASu5PIJHodEqrITCpkrUmUEfK9mCPL0yhrR65oZh+DBEV0UZXZF8oF8cyb2NEWZetEh+o5Hg",
	"vTfs5rVGa6PDHbthPbRGyEDfoQt2E4j1c+yQKj/DTBeKH4btx1y4NbI/sUAZg3UrygiehnZESmNZCIcF",
	"CPLIBVWiGKxPIoDRS8oXBHqkyEGQEASNVcX0Z0Lbs1ip2+1Y1VrjbXIX/kmzF3+vj/KIioxQLuWjUWrk",
	"oIQKKdBulEsYBIoshDMP+9yQOrtu0xVpOad3x+5I6xGPFkSEIdd1TT4eBIV9ibmCOoRCuaVKmwqVyoJj",
	"KNzQgZWQb2hkG91SU6+zDUaRdM6C5bkH4r3q7Eo4tnK/XY2M35Z3MFyODaXyduWZ/PMmdg8zptV1EP2c",
	"nwiKQBf/IC1JJPGahuT3Qkof5NAkn1iQXrHEegaILEMumEO5on3M0WTMs1Su9m2kLs9OdGwkPb+tjTy6",
	"c+XxFJcH5f8+QqSc+IVFtRGWSilHBXhBx47nEURVapNVDS9actAK63iq4+eNGVb53a78E21EbOrvl6xx",
	"VTL6Q+gH2DyP0OaSAKV15YpKKo3Oo8PSyVFbNQ4XbiTMvhEq5P0VXrign/1m1XqdQs5QWLCpQVQjCOiJ",
	"Sedm4uNerRI/CAANNfyAp0DB/cpyBKPz8jvItZQ2fMXoYr6Ipx9X8ODXtjIWdEBlGD2U3U5n/Wjj3Xid",
	"jcOUPdxOGg/VYj6i/EUmFGgzD22d5wKXA4inEKvlgNWGekeFCdzY5YA2OHebHmjbBQ537II2UbIHFXs9",
	"0JNaBsyG+lE8rwlTnGlDLTPlYc47yZq+KKYZxaOysZD2skPZzjiCk9CJFo6wMhk8ylJJlMPAouIWGFAW",
	"XA5fLpgAic6hqfJpoVgtxTQqC8yYkCNny46gspn5PrW4xXLwuteZhq/JkEKddWiffUXj1T+OBjoEHy87",
	"QfCJBb1UTdzYVs6/FfxyHE87d/uVj8KADeVymGe5ccHZ7bYJHqQZqsPeH6J32SS15mR2dLtuLC22uMZ7",
	"AA60ToEvwCqT1ADUCB7RvBTTpEx52qYYc2PeM00RMsZx1A28cLZ+V2Dqn/+dwq66WOD/YPe62XhEtYKb",
	"QZ2h8512zJmQq6HU812Gprw+6WCQhWsWu+rQG1dC3Fqg1Muw1a+I6mHXaDhIPQc6z3xAgTmLPPlYylq0",
	"0NrBML/m0P1DKxms3XRtYN0p6QPwyqk6Fwxqu01e15SlZ7bsoPaTm+ECmctYDmMgWAJH510l7/5XHlIJ",
	"XFwfTe5QkdEFr51jvh2/v/XocC+X/+EN0lBbZgtcwxNA9abAoke6+SMD6eOwLmAKmF2pFB5fpCghYKSO",
	"VkLe+kC5h58CrpdKasaH3hUPBwDIc4+vL4R1dCfe+YP7HTCsauhdGnQDhodp0eqO3ls10vsgVDaLRq7E",
	"s/Qfoo2OYL9m4vG5lnJzkR07Pi6R07n1X8QBP8v+nys+0jmqi0yGni471LOZSJHrtMhQuZHNvT9iF4gu",
	"kyP6twmYqhdsKhQj291ylfH2hWOjC2kvYCYkfiQA6fDe4sD4seC7rdAdaEEjBkJuQChhF8gbLKrDKwv3",
	"LO2M++tXMV3XJ7sTp2rr0qgenlV8BwJD/t7dq2el8xT3ve5pxVFks7w7ZfSSzkjGenx10wThpzyruz9p",
	"VN0icRcIaFxb0WP3X3acQF7D4Oc5orCRQTJ+Nq8BYYl4JlcVoZub8XZ9M/9OB6G8gqG2OQcaifX/A8Dd",
	"yPaHsbM/T2XCRySgZ40gp7amzs68eMXVzW/2bUQ1rdeF3UKb3l2gTeGyDXE7yh3UosYcqy6ToCnQwVIX",
	"koM+RyNZDvfobvoq0P0lcLbyyPBqAX4J1WUvtb7u+7tOmn5wgI84oMr7mp/LhZbrWwZH8Jl2i9DCGu6n",
	"qBiCXDiq23P4/MV3MC3kGYgsWHbkBdWLQ0nWy1LKpCRz58fGYf43C8KFFJa3f9Xk5LzR3QXkWUkM4Rkt",
	"z5yXsrR5ri+lntxzlDrPwp3VdB8U3ZJzPA5djQtt3fFvj357lFy+vvzfAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
