// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AttendanceRecordStatus.
const (
	AttendanceRecordStatusAbsent  AttendanceRecordStatus = "absent"
	AttendanceRecordStatusLate    AttendanceRecordStatus = "late"
	AttendanceRecordStatusPending AttendanceRecordStatus = "pending"
	AttendanceRecordStatusPresent AttendanceRecordStatus = "present"
)

// Valid indicates whether the value is a known member of the AttendanceRecordStatus enum.
func (e AttendanceRecordStatus) Valid() bool {
	switch e {
	case AttendanceRecordStatusAbsent:
		return true
	case AttendanceRecordStatusLate:
		return true
	case AttendanceRecordStatusPending:
		return true
	case AttendanceRecordStatusPresent:
		return true
	default:
		return false
	}
}

// Defines values for DailyLogRowStatus.
const (
	DailyLogRowStatusAbsent  DailyLogRowStatus = "absent"
	DailyLogRowStatusLate    DailyLogRowStatus = "late"
	DailyLogRowStatusPending DailyLogRowStatus = "pending"
	DailyLogRowStatusPresent DailyLogRowStatus = "present"
)

// Valid indicates whether the value is a known member of the DailyLogRowStatus enum.
func (e DailyLogRowStatus) Valid() bool {
	switch e {
	case DailyLogRowStatusAbsent:
		return true
	case DailyLogRowStatusLate:
		return true
	case DailyLogRowStatusPending:
		return true
	case DailyLogRowStatusPresent:
		return true
	default:
		return false
	}
}

// Defines values for EmployeeRole.
const (
	EmployeeRoleAdmin       EmployeeRole = "admin"
	EmployeeRoleEmployee    EmployeeRole = "employee"
	EmployeeRoleSupervisor  EmployeeRole = "supervisor"
	EmployeeRoleSystemOwner EmployeeRole = "system_owner"
)

// Valid indicates whether the value is a known member of the EmployeeRole enum.
func (e EmployeeRole) Valid() bool {
	switch e {
	case EmployeeRoleAdmin:
		return true
	case EmployeeRoleEmployee:
		return true
	case EmployeeRoleSupervisor:
		return true
	case EmployeeRoleSystemOwner:
		return true
	default:
		return false
	}
}

// Defines values for EmployeeStatus.
const (
	EmployeeStatusActive   EmployeeStatus = "active"
	EmployeeStatusInactive EmployeeStatus = "inactive"
)

// Valid indicates whether the value is a known member of the EmployeeStatus enum.
func (e EmployeeStatus) Valid() bool {
	switch e {
	case EmployeeStatusActive:
		return true
	case EmployeeStatusInactive:
		return true
	default:
		return false
	}
}

// Defines values for HolidaySource.
const (
	Manual    HolidaySource = "manual"
	NagerDate HolidaySource = "nager_date"
)

// Valid indicates whether the value is a known member of the HolidaySource enum.
func (e HolidaySource) Valid() bool {
	switch e {
	case Manual:
		return true
	case NagerDate:
		return true
	default:
		return false
	}
}

// Defines values for LeaveRequestStatus.
const (
	LeaveRequestStatusApproved LeaveRequestStatus = "approved"
	LeaveRequestStatusPending  LeaveRequestStatus = "pending"
	LeaveRequestStatusRejected LeaveRequestStatus = "rejected"
)

// Valid indicates whether the value is a known member of the LeaveRequestStatus enum.
func (e LeaveRequestStatus) Valid() bool {
	switch e {
	case LeaveRequestStatusApproved:
		return true
	case LeaveRequestStatusPending:
		return true
	case LeaveRequestStatusRejected:
		return true
	default:
		return false
	}
}

// Defines values for ReportExportStatus.
const (
	Failed     ReportExportStatus = "failed"
	Processing ReportExportStatus = "processing"
	Ready      ReportExportStatus = "ready"
)

// Valid indicates whether the value is a known member of the ReportExportStatus enum.
func (e ReportExportStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Processing:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for UpdateEmployeeRoleRequestRole.
const (
	UpdateEmployeeRoleRequestRoleAdmin      UpdateEmployeeRoleRequestRole = "admin"
	UpdateEmployeeRoleRequestRoleEmployee   UpdateEmployeeRoleRequestRole = "employee"
	UpdateEmployeeRoleRequestRoleSupervisor UpdateEmployeeRoleRequestRole = "supervisor"
)

// Valid indicates whether the value is a known member of the UpdateEmployeeRoleRequestRole enum.
func (e UpdateEmployeeRoleRequestRole) Valid() bool {
	switch e {
	case UpdateEmployeeRoleRequestRoleAdmin:
		return true
	case UpdateEmployeeRoleRequestRoleEmployee:
		return true
	case UpdateEmployeeRoleRequestRoleSupervisor:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin       UserRole = "admin"
	UserRoleEmployee    UserRole = "employee"
	UserRoleSupervisor  UserRole = "supervisor"
	UserRoleSystemOwner UserRole = "system_owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleEmployee:
		return true
	case UserRoleSupervisor:
		return true
	case UserRoleSystemOwner:
		return true
	default:
		return false
	}
}

// Defines values for ListEmployeesParamsRole.
const (
	ListEmployeesParamsRoleAdmin      ListEmployeesParamsRole = "admin"
	ListEmployeesParamsRoleEmployee   ListEmployeesParamsRole = "employee"
	ListEmployeesParamsRoleSupervisor ListEmployeesParamsRole = "supervisor"
)

// Valid indicates whether the value is a known member of the ListEmployeesParamsRole enum.
func (e ListEmployeesParamsRole) Valid() bool {
	switch e {
	case ListEmployeesParamsRoleAdmin:
		return true
	case ListEmployeesParamsRoleEmployee:
		return true
	case ListEmployeesParamsRoleSupervisor:
		return true
	default:
		return false
	}
}

// Defines values for ListEmployeesParamsStatus.
const (
	ListEmployeesParamsStatusActive     ListEmployeesParamsStatus = "active"
	ListEmployeesParamsStatusOffboarded ListEmployeesParamsStatus = "offboarded"
)

// Valid indicates whether the value is a known member of the ListEmployeesParamsStatus enum.
func (e ListEmployeesParamsStatus) Valid() bool {
	switch e {
	case ListEmployeesParamsStatusActive:
		return true
	case ListEmployeesParamsStatusOffboarded:
		return true
	default:
		return false
	}
}

// Defines values for GetMyNotificationsParamsUnread.
const (
	False GetMyNotificationsParamsUnread = "false"
	True  GetMyNotificationsParamsUnread = "true"
)

// Valid indicates whether the value is a known member of the GetMyNotificationsParamsUnread enum.
func (e GetMyNotificationsParamsUnread) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// AttendanceRecord defines model for AttendanceRecord.
type AttendanceRecord struct {
	AutoClosed bool `json:"auto_closed"`

	// CheckInAt Example: 09:03:00
	CheckInAt *string `json:"check_in_at,omitempty"`

	// CheckOutAt Example: 17:05:00
	CheckOutAt *string                `json:"check_out_at,omitempty"`
	EmployeeId string                 `json:"employee_id"`
	Id         string                 `json:"id"`
	Status     AttendanceRecordStatus `json:"status"`
	WorkDate   openapi_types.Date     `json:"work_date"`
}

// AttendanceRecordStatus defines model for AttendanceRecord.Status.
type AttendanceRecordStatus string

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string    `json:"access_token"`
	ExpiresAt   time.Time `json:"expires_at"`
	User        User      `json:"user"`
}

// CheckInRequest defines model for CheckInRequest.
type CheckInRequest struct {
	// IdempotencyKey Client-generated, stable across retries of the same logical attempt.
	IdempotencyKey string `json:"idempotency_key"`
	QrToken        string `json:"qr_token"`
}

// CheckOutRequest defines model for CheckOutRequest.
type CheckOutRequest struct {
	IdempotencyKey string `json:"idempotency_key"`
}

// CompleteRegistrationRequest defines model for CompleteRegistrationRequest.
type CompleteRegistrationRequest struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`

	// PhoneNumber Optional, same reasoning as student_id.
	PhoneNumber *string `json:"phone_number,omitempty"`
	StudentGen  string  `json:"student_gen"`

	// StudentId Optional -- adding it as required would break registration for anyone already mid-flow.
	StudentId *string `json:"student_id,omitempty"`
}

// CreateHolidayRequest defines model for CreateHolidayRequest.
type CreateHolidayRequest struct {
	Date      openapi_types.Date `json:"date"`
	LocalName *string            `json:"local_name,omitempty"`
	Name      string             `json:"name"`
}

// CreateKioskDeviceRequest defines model for CreateKioskDeviceRequest.
type CreateKioskDeviceRequest struct {
	Name string `json:"name"`
}

// CreateLeaveRequestRequest defines model for CreateLeaveRequestRequest.
type CreateLeaveRequestRequest struct {
	EndDate openapi_types.Date `json:"end_date"`

	// LeaveType Free-text leave category (ประเภทการลา), distinct from reason.
	LeaveType *string            `json:"leave_type,omitempty"`
	Reason    *string            `json:"reason,omitempty"`
	StartDate openapi_types.Date `json:"start_date"`
}

// DailyLogRow defines model for DailyLogRow.
type DailyLogRow struct {
	AutoClosed bool               `json:"auto_closed"`
	CheckInAt  *string            `json:"check_in_at,omitempty"`
	CheckOutAt *string            `json:"check_out_at,omitempty"`
	Date       openapi_types.Date `json:"date"`
	EmployeeId string             `json:"employee_id"`
	FirstName  *string            `json:"first_name,omitempty"`
	LastName   *string            `json:"last_name,omitempty"`
	Status     DailyLogRowStatus  `json:"status"`
}

// DailyLogRowStatus defines model for DailyLogRow.Status.
type DailyLogRowStatus string

// Employee defines model for Employee.
type Employee struct {
	CreatedAt               time.Time      `json:"created_at"`
	FirstName               *string        `json:"first_name,omitempty"`
	Id                      string         `json:"id"`
	LastName                *string        `json:"last_name,omitempty"`
	LineDisplayName         *string        `json:"line_display_name,omitempty"`
	LinePictureUrl          *string        `json:"line_picture_url,omitempty"`
	OffboardedAt            *time.Time     `json:"offboarded_at,omitempty"`
	OffboardedReason        *string        `json:"offboarded_reason,omitempty"`
	PhoneNumber             *string        `json:"phone_number,omitempty"`
	RegistrationCompletedAt *time.Time     `json:"registration_completed_at,omitempty"`
	Role                    EmployeeRole   `json:"role"`
	Status                  EmployeeStatus `json:"status"`
	StudentGen              *string        `json:"student_gen,omitempty"`
	StudentId               *string        `json:"student_id,omitempty"`
	TeamId                  *string        `json:"team_id,omitempty"`
}

// EmployeeRole defines model for Employee.Role.
type EmployeeRole string

// EmployeeStatus defines model for Employee.Status.
type EmployeeStatus string

// EmployeeListResponse defines model for EmployeeListResponse.
type EmployeeListResponse struct {
	Employees []Employee `json:"employees"`

	// Total Total matching rows before limit/offset pagination.
	Total int `json:"total"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Holiday defines model for Holiday.
type Holiday struct {
	Date      openapi_types.Date `json:"date"`
	Id        string             `json:"id"`
	LocalName *string            `json:"local_name,omitempty"`
	Name      string             `json:"name"`
	Source    HolidaySource      `json:"source"`
}

// HolidaySource defines model for Holiday.Source.
type HolidaySource string

// KioskDevice defines model for KioskDevice.
type KioskDevice struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *string   `json:"created_by,omitempty"`
	DeviceId  string    `json:"device_id"`
	Id        string    `json:"id"`

	// MaskedToken Example: ••••••••ab12
	MaskedToken string `json:"masked_token"`
	Name        string `json:"name"`

	// RevokedAt null for an active device. GET /kiosk/devices returns the latest row per device (active or revoked) — see ListAll.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`
}

// KioskDeviceWithToken defines model for KioskDeviceWithToken.
type KioskDeviceWithToken struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy *string   `json:"created_by,omitempty"`
	DeviceId  string    `json:"device_id"`
	Id        string    `json:"id"`

	// MaskedToken Example: ••••••••ab12
	MaskedToken string `json:"masked_token"`
	Name        string `json:"name"`

	// RevokedAt null for an active device. GET /kiosk/devices returns the latest row per device (active or revoked) — see ListAll.
	RevokedAt *time.Time `json:"revoked_at,omitempty"`

	// Token The full raw device token. Only ever returned here and from rotate.
	Token string `json:"token"`
}

// LeaveRequest defines model for LeaveRequest.
type LeaveRequest struct {
	CreatedAt  time.Time          `json:"created_at"`
	DecidedAt  *time.Time         `json:"decided_at,omitempty"`
	DecidedBy  *string            `json:"decided_by,omitempty"`
	EmployeeId string             `json:"employee_id"`
	EndDate    openapi_types.Date `json:"end_date"`
	Id         string             `json:"id"`
	LeaveType  *string            `json:"leave_type,omitempty"`
	Reason     *string            `json:"reason,omitempty"`
	StartDate  openapi_types.Date `json:"start_date"`
	Status     LeaveRequestStatus `json:"status"`
}

// LeaveRequestStatus defines model for LeaveRequest.Status.
type LeaveRequestStatus string

// LineAuthorizeResponse defines model for LineAuthorizeResponse.
type LineAuthorizeResponse struct {
	AuthorizeUrl string `json:"authorize_url"`
}

// LineLoginRequest defines model for LineLoginRequest.
type LineLoginRequest struct {
	Code        string `json:"code"`
	RedirectUri string `json:"redirect_uri"`

	// State Must equal the state returned by /auth/line/authorize.
	State string `json:"state"`
}

// MonthlyReportRow defines model for MonthlyReportRow.
type MonthlyReportRow struct {
	AbsentCount int     `json:"absent_count"`
	EmployeeId  string  `json:"employee_id"`
	FirstName   *string `json:"first_name,omitempty"`
	LastName    *string `json:"last_name,omitempty"`
	LateCount   int     `json:"late_count"`
	LateMinutes int     `json:"late_minutes"`
	LeaveDays   int     `json:"leave_days"`
	WorkDays    int     `json:"work_days"`

	// WorkedHours Capped to each day's scheduled shift length — never counts time outside the scheduled window, even with a real late checkout.
	WorkedHours float32 `json:"worked_hours"`
}

// Notification defines model for Notification.
type Notification struct {
	Body      *string    `json:"body,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	Id        string     `json:"id"`
	ReadAt    *time.Time `json:"read_at,omitempty"`
	Title     string     `json:"title"`

	// Type Example: leave.decided
	Type string `json:"type"`
}

// OffboardEmployeeRequest defines model for OffboardEmployeeRequest.
type OffboardEmployeeRequest struct {
	Reason *string `json:"reason,omitempty"`
}

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// QRTokenResponse defines model for QRTokenResponse.
type QRTokenResponse struct {
	DeviceName string    `json:"device_name"`
	ExpiresAt  time.Time `json:"expires_at"`
	Token      string    `json:"token"`
}

// ReplaceScheduleRequest defines model for ReplaceScheduleRequest.
type ReplaceScheduleRequest struct {
	Rows []ReplaceScheduleRow `json:"rows"`
}

// ReplaceScheduleRow defines model for ReplaceScheduleRow.
type ReplaceScheduleRow struct {
	DayOfWeek     int                 `json:"day_of_week"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to,omitempty"`

	// EndTime Example: 17:00:00
	EndTime string `json:"end_time"`

	// StartTime Example: 09:00:00
	StartTime string `json:"start_time"`
}

// ReportExport defines model for ReportExport.
type ReportExport struct {
	Error  *string            `json:"error,omitempty"`
	Id     string             `json:"id"`
	Month  string             `json:"month"`
	Status ReportExportStatus `json:"status"`
}

// ReportExportStatus defines model for ReportExport.Status.
type ReportExportStatus string

// RequestExportRequest defines model for RequestExportRequest.
type RequestExportRequest struct {
	Month string `json:"month"`
}

// UpdateEmployeeRequest defines model for UpdateEmployeeRequest.
type UpdateEmployeeRequest struct {
	FirstName   string  `json:"first_name"`
	LastName    string  `json:"last_name"`
	PhoneNumber *string `json:"phone_number,omitempty"`
	StudentGen  *string `json:"student_gen,omitempty"`
	StudentId   *string `json:"student_id,omitempty"`
	TeamId      *string `json:"team_id,omitempty"`
}

// UpdateEmployeeRoleRequest defines model for UpdateEmployeeRoleRequest.
type UpdateEmployeeRoleRequest struct {
	// Role system_owner is rejected — see the endpoint summary.
	Role UpdateEmployeeRoleRequestRole `json:"role"`
}

// UpdateEmployeeRoleRequestRole system_owner is rejected — see the endpoint summary.
type UpdateEmployeeRoleRequestRole string

// UpdateHolidayRequest defines model for UpdateHolidayRequest.
type UpdateHolidayRequest struct {
	LocalName *string `json:"local_name,omitempty"`
	Name      string  `json:"name"`
}

// User defines model for User.
type User struct {
	DisplayName  *string  `json:"display_name,omitempty"`
	FirstName    *string  `json:"first_name,omitempty"`
	Id           string   `json:"id"`
	IsRegistered bool     `json:"is_registered"`
	LastName     *string  `json:"last_name,omitempty"`
	PhoneNumber  *string  `json:"phone_number,omitempty"`
	PictureUrl   *string  `json:"picture_url,omitempty"`
	Role         UserRole `json:"role"`
	StudentId    *string  `json:"student_id,omitempty"`
}

// UserRole defines model for User.Role.
type UserRole string

// WorkSchedule defines model for WorkSchedule.
type WorkSchedule struct {
	// DayOfWeek 0 = Sunday
	DayOfWeek     int                 `json:"day_of_week"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EffectiveTo   *openapi_types.Date `json:"effective_to,omitempty"`
	EmployeeId    string              `json:"employee_id"`

	// EndTime Example: 17:00:00
	EndTime string `json:"end_time"`
	Id      string `json:"id"`

	// StartTime Example: 09:00:00
	StartTime string `json:"start_time"`
}

// DeviceId defines model for DeviceId.
type DeviceId = string

// EmployeeId defines model for EmployeeId.
type EmployeeId = string

// EmployeeUserId defines model for EmployeeUserId.
type EmployeeUserId = string

// ExportId defines model for ExportId.
type ExportId = string

// HolidayId defines model for HolidayId.
type HolidayId = string

// LeaveRequestId defines model for LeaveRequestId.
type LeaveRequestId = string

// Month Example: 2026-03
type Month = string

// NotificationId defines model for NotificationId.
type NotificationId = string

// LineAuthorizeParams defines parameters for LineAuthorize.
type LineAuthorizeParams struct {
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`
}

// ListEmployeesParams defines parameters for ListEmployees.
type ListEmployeesParams struct {
	TeamId *string                  `form:"team_id,omitempty" json:"team_id,omitempty"`
	Role   *ListEmployeesParamsRole `form:"role,omitempty" json:"role,omitempty"`

	// Status Filters on offboarded_at, not the separate active/inactive status column.
	Status *ListEmployeesParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Search Matched against first_name, last_name, and line_display_name.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int    `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListEmployeesParamsRole defines parameters for ListEmployees.
type ListEmployeesParamsRole string

// ListEmployeesParamsStatus defines parameters for ListEmployees.
type ListEmployeesParamsStatus string

// ListHolidaysParams defines parameters for ListHolidays.
type ListHolidaysParams struct {
	From openapi_types.Date `form:"from" json:"from"`
	To   openapi_types.Date `form:"to" json:"to"`
}

// GetKioskQRTokenParams defines parameters for GetKioskQRToken.
type GetKioskQRTokenParams struct {
	Token string `form:"token" json:"token"`
}

// GetMyNotificationsParams defines parameters for GetMyNotifications.
type GetMyNotificationsParams struct {
	Unread *GetMyNotificationsParamsUnread `form:"unread,omitempty" json:"unread,omitempty"`
}

// GetMyNotificationsParamsUnread defines parameters for GetMyNotifications.
type GetMyNotificationsParamsUnread string

// GetDailyLogParams defines parameters for GetDailyLog.
type GetDailyLogParams struct {
	Month      Month   `form:"month" json:"month"`
	EmployeeId *string `form:"employee_id,omitempty" json:"employee_id,omitempty"`
}

// GetMonthlyReportParams defines parameters for GetMonthlyReport.
type GetMonthlyReportParams struct {
	Month Month `form:"month" json:"month"`
}

// CheckInJSONRequestBody defines body for CheckIn for application/json ContentType.
type CheckInJSONRequestBody = CheckInRequest

// CheckOutJSONRequestBody defines body for CheckOut for application/json ContentType.
type CheckOutJSONRequestBody = CheckOutRequest

// LineLoginJSONRequestBody defines body for LineLogin for application/json ContentType.
type LineLoginJSONRequestBody = LineLoginRequest

// PasswordLoginJSONRequestBody defines body for PasswordLogin for application/json ContentType.
type PasswordLoginJSONRequestBody = PasswordLoginRequest

// CompleteRegistrationJSONRequestBody defines body for CompleteRegistration for application/json ContentType.
type CompleteRegistrationJSONRequestBody = CompleteRegistrationRequest

// UpdateEmployeeJSONRequestBody defines body for UpdateEmployee for application/json ContentType.
type UpdateEmployeeJSONRequestBody = UpdateEmployeeRequest

// OffboardEmployeeJSONRequestBody defines body for OffboardEmployee for application/json ContentType.
type OffboardEmployeeJSONRequestBody = OffboardEmployeeRequest

// UpdateEmployeeRoleJSONRequestBody defines body for UpdateEmployeeRole for application/json ContentType.
type UpdateEmployeeRoleJSONRequestBody = UpdateEmployeeRoleRequest

// CreateHolidayJSONRequestBody defines body for CreateHoliday for application/json ContentType.
type CreateHolidayJSONRequestBody = CreateHolidayRequest

// UpdateHolidayJSONRequestBody defines body for UpdateHoliday for application/json ContentType.
type UpdateHolidayJSONRequestBody = UpdateHolidayRequest

// CreateKioskDeviceJSONRequestBody defines body for CreateKioskDevice for application/json ContentType.
type CreateKioskDeviceJSONRequestBody = CreateKioskDeviceRequest

// CreateLeaveRequestJSONRequestBody defines body for CreateLeaveRequest for application/json ContentType.
type CreateLeaveRequestJSONRequestBody = CreateLeaveRequestRequest

// RequestReportExportJSONRequestBody defines body for RequestReportExport for application/json ContentType.
type RequestReportExportJSONRequestBody = RequestExportRequest

// ReplaceEmployeeScheduleJSONRequestBody defines body for ReplaceEmployeeSchedule for application/json ContentType.
type ReplaceEmployeeScheduleJSONRequestBody = ReplaceScheduleRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H1bjxu5lf9XOdA/gLsRXdozk/yT/uP/0DPjTHrj27Q9ycPY26CKRxLTLLJMslpWjAay+xkC7MO+LLLY",
	"90WenG9j5JMseMi6SVVSqW+2kwUGGLfEYh2S5/I7N+rdINFpphUqZwfH7wYZMyxFh4b++hYvRYKn3P9b",
	"qMHxIGNuMRgOFEtxcDzgxdfDgcE3uTDIB8fO5Dgc2GSBKfPPuVXmx1pnhJoPrq6Gg0dpJvUKu+fFasD1",
	"Zv7BoumcXew969tMG3d78/1aS8HZ6vYmfIzsEs/wTY72Fsl8opVblJO9ydGsqtlS+nLbhPiWpZn0Y784",
	"+uLno6MvB0NPkUPjp/vnV6/4u6+uRv5/X1z9ZDBsIeCpdmImEuaEVre1rKviS+LvE+dQcaYSPMNEG3pH",
	"ZnSGxgmkESx3+jyR2iKvTTfVWiJTg6vhIFlgcnEu1DlzzVUf/fL46MvjoyNPai4lm/pPA3lrRBWT6Nxt",
	"zPLw/x4f/aznLIXYnAvesvThoONj65jLabGo8nRw/OMgQ8X9l8NBZtCicoPhQDKHg+GATenv1y2vX2pz",
	"cc79sON3g5k2qV/LgIfnNk+3OrMfwyHWya/PVlI4bJxGRYKe/h4T50k4yd3iDG2mlcWWs0wStPbc6QtU",
	"rTuBbzNh0MZDaCxh5ETaso7hILdo/OifGJwNjgf/Z1Lp00nktIlXRxtrblDTeHectG2B33hGOVVR1jeX",
	"KDimmXaoktX5Ba78RxxtYkTmhWhwPPhGClRuNEeFhjnkQ7DOMxWwxGhrwaAzAi3oGbgFgmUpgtRzkTAJ",
	"XnjTzI3btuGN6dzXtXWXI4cb1Hau+Fnu9lnyLmbr8Vbt5c/hGc6FdYZUUCcFM2GsOw/6qIWrJNv2bbbQ",
	"Cs9Vnk4DHzWP6xn9g8lhOAmDzGol1ByYBetyjsqdC956IsXX8w5mrx7vfi2MRsC41wUgnH9nsY+w1Lnk",
	"MDXILsDUNglm2gBTK60QmDTI+ApSwUczqZfjnXqgtpP1fWsupvW8DDKH0bB2HlRP5TQcSJ0w2X1mHV+s",
	"LSZOToO7af6N0PYi4KxOuvu9b8eL6iCh802o+Hn/XfIznoeP1znoVwZx5PCtAxoFCXM412YFBx/e//uH",
	"9//54f1/f/jrHz+8/48P7//tw/t/+fD+L/Thf314/5fDIXBhnVCJg5nRaeT6ViYPX3WZNeOuaY9qzw6r",
	"PWnb22+ZkKvHen6mlzcHD3vjhJ0P9D7LXdihqeN2vreh83aOvh0E0i5+TVTRG0kUnsTmoSYkTXwvkLDn",
	"7nWcwX6bKoXCcy5sJtlqz6cykbjc4HluZK+H9Gw21czw7buyzzSVXO98at2A7nygbq7Ok2job0a50RLr",
	"7GtX1mF6rpcKjWc2ngqPd2yeobkUVpsaY7Zi6U2JYIkTl54YoeI/X+82+j0krw4Cdg53yNJ+Y9sAPu1S",
	"TQZrkrRNBB8Lb7C6QH2xjQELOkztLjReivZV+VJmDFvR39oxuWnNXvqPIWUuWXgsZPTSwhRn2iBIkQo3",
	"0bOZRQcZmwtFjFWzVkI5nLc4ABXlxXvbduHXyKRbvCj5obn6Gp+ULqO+6GPf/GOt7wsY6gbgqUt7NTDV",
	"TlbrBF9W5yZpSJticzSFtU6ZyhtbuY0j6xCtnLltV2oo7XYsQvHMdNXPjtOr93TsU2YvkFd+WcUif/vj",
	"n1v/Y9OHXwz2OQyDl/qiXHpTaPyiojsAQWVBWMYYvnv0EiYXfk8n4SNyPHOjLHmd3tJb58UMMjTxKTiI",
	"k2gD8bWH8Lc//gksIngdcSLl+JVXs9fR4a3cUW56ySKNLd2pwWpc8zvhFi+Lg2BSPpsNjn/crqfqPHc1",
	"XGe68lTXNNUCYeY33rBlsXE0dAzPlFwBXqKJe40cFmgQmOIRZ2vHHO720sKrNxf8ei0UeTuSwjERN0UW",
	"xRw9pW0XGN7LS+pShw3nqQdo6Q2I9nJ8toNvlmVGX2IIsfpDbqDl/sG8dn+qPxR4LBSe5G6hjfgDbgnw",
	"FUMK5Lqd0Obwrvc+1nPRHftJNO/SjFwYTNx5bkRn2LXFcX6SWwf4JmcyBOD8qEpgpyuYeLInHqdPygXs",
	"llmic42qgoa2lVPwX67OMNPGtTu35IedJzpXrrbAEu18ZJ/S25BtxNH3qVC5i/p0cwRJKGerju9jhHrb",
	"18jPFzoPubS1OCzLMuTgNCBLFsDZ6oEFr/l5LpGDXYiZA4lq7hZk5BQpblqPBa/2QOfOCo6BS8oHl0Jx",
	"vRx6Pa9gKdwCGBhkkmwqUPxA5y7YyUhzdJ264GkjHL+yg8bWru3jsMkVjT1c25E2pqsnfDYZbqp5P/V9",
	"HSvTwaIG2c0sjxNOtiuIQvVXqIw2axxtVb+cCQ0p3rJTjT6LDnbhAXVqtc6w2lXLrM+ZtUtt+HZFmcVR",
	"ja0sP+xIrPQLfJYjh9WEbcv//owQWLf9iICvE+1eJz/UMyvSmgaq09O2oDPMJEvwRZT+7uPUy/7u8fqk",
	"ernpKK8RT/P3IbDNjnC2Otez8yXihf8zZW9F6nHIz4eDVKjw76Nhm3mZzZA8gnOPXvtFOctHnG57YDcy",
	"VPycTnojSXsUkrQdaGzzmaNfdj2zEces9qcxXY2ajc3oOAxtXChmaImjGKPNTaKTaVEu0AdhGp2gtQFk",
	"UpLIu21MyN74sqg/2BLJiOIQFtwpGyXZ+9Um1AkKU7SR8EPmGWunur3VBOInE/PrSOb12Ce9VZfJFtRc",
	"D7iCsFB4K2WAwKMkVDzTQjmweZoysxqTCMXw6p4h2g0NKLetbFdi8lbyjd27G0sU1vTuvqmB20liCHse",
	"AvBourJi+wH9vfl/3+zGHQT39xDALYH05la2nfzvtLkojO9Oy9uUqCP4//AiV5ytKOz1SRvlHuGa/Yx2",
	"d6XUzWx5S2jklsy7pw6T3Ai38geeRpcJmUFzkgcLF/76VbG9//S7l4NYDUcCSN9WS1g4l4WCOaFmepNB",
	"Cm1NZUGhiA5Onp9SxJeKdjgifPjrv354/6cP7/8MLjfq+dmzMbxcCAs2w8TraXJeF8wgh0QrZ1jiYIpu",
	"iajou+80TFlygYpTmNJ/VJYuwcxo5V8NCRU1lbqeoxVzNU7DM988e/ry7PTrH16ePv3Of+bpy4z22zZa",
	"egc60eoSlV+VjX5x8NkG5SpOnp8OhoNLNDbKxvjh+IgylhkqlonB8eDL8dE4VjguaOsn1bZMyO0eieDT",
	"6mAAvCCWlY1FXVcsZUTrvo7ObkJLpCdYlsnoHE9+H92zqtBxG6Rfqxq7arKllyr6ILhFRP0XR0e39vaN",
	"Ikt6/1o4JO4QGBqC3O/uV4GItfiYINwIRRkZaAPrFV307MPOZydCXTIpOIQSvBAfH/qJPH+VEwsLceAk",
	"eGU8JiugTMHSi365+aLvzyDRvKqAyi1yekHxAXEEchAKnObRpSoEmDIDddH98fXVa29gCLUMjge/RSNm",
	"K2BgE6YUcvj+DDK2kppxOPC8z7yBGwKRvRqCX7TEUW7xkEQibDKttmDNIfiTy53fWv+50qO5YQmOMjRC",
	"cwofTUJwBwLmBjZnQlkXoFVUBrUgFgkaLc5LlV/fpkjo3O2QiWe5u0uhqBUWfrJSoXPXXyz2FAWSnhZp",
	"6OTsp9ptMG8rZ3uqr8HazyUTCoQasSwrw5UhAqrh+7Oh/1/CUjQMrMNsSAlCz4EzqZeQE9oGt2B+yyj2",
	"ENhcGzEXislqymgkStbcDKr7xc+xhTEb2QjS+VXPxI/t5fJrcff+9eqv75AF27MqLXxYDAoVnj+cPQZh",
	"bY5e2aCzMUfhFYvSHgUkWl8ItIc7mbWxK8QmJR98jXOhgMHj06ePqABZjeGJUM4Cg29enP2q9lKmQMSU",
	"bCBgCFOhOIGLFJwGu9DGjaS4RA4e1VAiNBI5jAqxSj7TG9nGip0uyaVhufWMpz2eKbI0wgImC42cMAsw",
	"TyvxAZQcAjrgmoRJGQYpDmluPeoBUq5O1zM8YeWbTEqfd6vOMm91R7pzIy9238qzXuffwrBEG9g8SRA5",
	"8jG88HzKVHX8BmcG7WIU2CYwAxzYRMesDO31oVdxjHNBXOA0HV2xKJhqHkxbh4olRvIwYJIZPRMSAd8m",
	"C6bmCDHURU9+ufnkSUL5E89QHAlqeLy7JiGPismikIQ1NxmXQAiVYIBFS+i1xkjbeagR1r8jPmpNHfzD",
	"89IWjVmkOrzFLXMdXQx4Gg1790PX5b0f4oyTYrqgogPk8/qwHo4zWiJZcDLEtGH+EzLSXKNVD5wnsaHq",
	"IxUWmPGbo511JmRMde5GejaaesV54L296B9OkpRPLCKnlx4O/dsM6WSlwZv6PCsDgGsKVc+34tDH4fsN",
	"FvyqReT1fB5oXNuwMypYCqo/N8Yr+sg1AW+BRXOJZmQFxxppaTcI+Q7dExzcoVzEpqVNUBrppx6la8PL",
	"fTDhdxhMrt8S76gn5P3nRVNV2Kq4nd3HeBYGvIyJthvt2533lfXuFWuJBG2c2FNcNnY/orddhzcsjo7w",
	"fXSBm2y7zuVUQBY1W4tODJZIrZHTOMQQztziFLY0Zt2Vg7ilB+yebVSXLNZJg7KUvQfujl1cM4GS2/uR",
	"4mI7gfIIo1DDoqgewb+jMB1dQt6o8+5wy6x7VKup7uGWFbmtrY3QHR5dLGav+p2vnUna6J0S0lPtfYVG",
	"Z4V3foMmtOgX5/0fikNNioBUEZpJtMxTFaKZbcSXdXct5Bd9BtWrexH9hLlkgbyMClXZoiGUCZ3gbW10",
	"poy7yERmksV1Toeq8tserBXjtz8ZKvm3P3qXTnlr10OL6D8pmhFKwSgj5NRMEGrFii6FqjHhZhGhL9sq",
	"2aQMSVfPncT9k4r3J41s2V4K42UtrgjB89ZmNYQZiUdoWla8WJpH5t822gYnhgoe7APwJ2cUk6FMnBi8",
	"VBRw4CV5JDVFrZyGV6WwvhoMIVfhdUWxuVsIS5AzBAtoufDD6QNbkSqFdUMw2huywPDFV6NMJBdogBud",
	"eZxqSyBaHuLkneBX20Bf2b2yoeDauKoaMlm7G+NemLiNcevH+nGZ0c/x1ZbElp9ipnPF94erWjUXmXlp",
	"3TzPZt3D7Rzp7QOh9iqWe4ZA21iqPLEQ/90NgCrj5Dmsqjf4e2THR1w4KCJQAfAFL/ygw0RHUHQ4hjMd",
	"dWyBBfwezDW4hdH5fOE1oDCgl6r0rC1MUeolqcqiiXsIqTdBFpUVBFI8xNDKhvLkag6Wc+FGUs8BFV1C",
	"0aEdJwU13V7CeqHrpypZXQW5n6Js1fDgRxSTkKZlZo4Uorq2BHWkt6qihpjOqq96H6l7oWduxJEcHqYq",
	"cHDQQPST6WoSaq0DuvDuToh5hXr/BTM8zsKHzdqGMZxRjRuFIiO1o2ryYo8oQdKMx4VvuoSrqHbqZbHO",
	"ghP0OVitWk3hJyRdpGH7Wi06mo8uexTcoY1EDjEFEW6DSfVlDP5QfFf74YTE65MUQe47sHTfxHyIqpcj",
	"eFrqsrICZxhZohCGb6MxIn3m/BYW0fDOKPSlYNAIPpN5HUYRzoxOtaPaEfp/zXgKCyfPT0tBXFCn9x+2",
	"gf/QDH6XUd9Gu3kLw77wjJFQXD3P1sJ/j8UlKs9xlGSPiwqVr9ujNr8uBvUK2lAF3LYc+s67XjqCQfpG",
	"s97Un+rVnFF05292ZGycVLGpIBQYLxhefLn3ZGG6AlrELoVT0yV+0ydO30+o0PMELGr0M6I3LMMLM+Pk",
	"/k9XJNCbIcMx+VztAeT6TVF3FTluu42ql9V5eHuCXHBKJ2dA7BbbN1xcP+OKjT6HiNIJ92Ao3BAhVyNU",
	"FNgpOK2psMpATIBfm4z0LX1eMdJ+IKi6A7RFcbTYxuLMIhj8fPb824iBi10ew0loSI3g2JvaUtSZQfXA",
	"gc0pl1VkyW2FpUchf5wX+WOSD/SLC9g55tCz3HVB19s6sLsCrNfRGkf3qTV6o9XbSjLdYWylWNNNQisl",
	"Zz+wQDURVTPPGJ6Gtm0CphbCBTPE8sgF1doyqG6voQtPuMawopkUGQgSgqCxSqDYuDhlK7CqXSFiB/eB",
	"T5p3luzEKJG0YfuNL+fiM9JzhFn8aa+AzieuYRjosRBujinrYLoWPISNW27ggMWrWXhxo8uCWUhz6UQm",
	"ERbCOm3ohla6mMoumKGtUVjN+/9CzI9Ku3FJr8aZJJ9IOFsWpVAh42GhRbcAqPpB3yWIarke856BVOsl",
	"Pp28fF1Q9fkwejiXWMdRZ/VQCluWtAmVyJxjyJPRlUShFqRRCeaWmm6zsMGcx6BXlnmJOShvJwrcf9iu",
	"ACfvimvoryZBYrbVAPnvm7y7Hwwob8TvB9siU0RJ/iRtYCTxmibwN0JK757RJA8sSKpCCLWmINIUuWAO",
	"5SqkatGkzG+pXO06SF3cjtNxkPT9XR3k0b0rj6e43Ks26zPklFO/sKg2wlLj3XD4lhJF89JixoWxshlJ",
	"S07WrMZPdf55Y0Zl7V1X5IwOIl4A0rM2qCwU/BR6NdbvLmnr0gAquZMrKndtdIXtV+pX4I769XFrob4n",
	"QrkIJt66oJ/9YdX60EI9l7BgE4OoxhC4JxYENkM2B7UuiVDkxEJ/ReCnQMFhaTmC0Xn5W8i0lDa8hWKq",
	"8X67FTz8WZU8pFt1RhGhbIfL9cvr7gcvN67L6wGYaTyUi/mMIi+pUKDNPLTcXgpcDiHeM1cuB6w21Ncr",
	"TNiNbQC0sXN3iUDb7k2/Zwja5JIdXLETgZ7WYnc21PbGG/mKarHadX33Eu99kU9T8qRlYyHtJaFFbmcM",
	"p6FLMFxSyGRAlIWSKDOuFhW3wIDi93L0csEESHQOTRkJDI0EUkyjssCUCTl2tujWKhrND6n9MJbqV33o",
	"NLwiQwp10aF9dhX0r/5xNNC+lYDtTPDAUumIXCOqZecpuR3vs+zGlSdhwJpy2Q9Zrv0a0922cO6lGcrr",
	"PD9FdNkkdXepxtrSYr1GcXveftYp7Auw0iQ1GGoMJzQv+TQJU562KcaonkemCULKOI67GS/cR7TNMfXf",
	"/52yXXl17P+y3etmUxhlOW6H61Tt7szddqZ+02bPtHuu/FJbewY8/qEL3KRt7XC4l9R44/LQHoasuQUf",
	"yY55LyfasMYBDiHVJDkJqthLUeKdGdLxV1inbHMkIDJ58eTF5PHp00ejLLcL4heFElbo4KBxFYLNMHlg",
	"4VW4d3TkYUu8MWSCNmGSKHk1AGpkBWZtnsbbFOg9oxLw0NULz8/gF4UYFE0gVcSuyZ1RJbItFZxPmLmo",
	"n9BZ4L39VOLaDwj2C9n5N1OfG7uhwvqq9faMkqBK18CBNlQ3q+aUyWRK+1Ml5jjcj8M88RQqib/f1o/b",
	"4mL9QcWeiQlnQq5GUs+36ZHix4/2Ppjw05JdhThrd4ffWbyll1qp/8BTn4yWHw5Shx8J2afCJo178rnk",
	"9Wmhtbu//JpDgyetZFh5+9pA1Qxf74yg0rnaaZNCq5prEib95Ga0QOZSlsEEiC2Bo/Me16XAZalhCsbF",
	"6n7TDqQVPfnaZah3Ez5ovX+0V+Tgi1ukobbMtupu+gZQvckx75G1+syY9FFYF5VI25VK4NHbBCUEHqlz",
	"K3FedSutZz8FXC+V1IwH00ipUQoAxMdD3nUFB5cPDzvYcGc31xob7llIXfwu8Z1i/V0sVNwHEHcltpZ+",
	"kp00gcJr5i+eaynXF9lx4pOCczqP/ts44KOc/6XiY52hepvKUNRqR3o2EwlyneQpKje2mUcEdoHoUjmm",
	"/zcZpiyGnQrFyHa3/NDyZt/f+K20b2EmJH4mDNLVJhIGxpcFF3CFbk8LGnkghBiFEnaBvLFFdfZKww9y",
	"bHXr6r/ZcV1Mdi+gauPXRXogq/gMhA35e4dXzwrwFM+9jrTiKLJZHk4VRUSxcqjqO/X8U1zHuDsmUF4U",
	"fB8c0LiZuMfpv+y4ZLJig49zC81aINr42aj6aol4IVcloeuH8a548LRfu3ftcK7XbXUbMOEzOtmPk+D0",
	"Hol3vetOTm1NnaXJ8Xcybv+w78Kraf3NkTuoU74PblO4bOO4LVlTqtFljpXNcDQFutgDpy/RSJbBAf1e",
	"e+no/hQ4W3nO8GoBfgrlfd61xpbDbZcJfnIMH/lgrdtuudCy+jmqMXytQ4t3cQVxuSHIhaPyHw7fvPgt",
	"THN5ASINlh15TmUnobLDy1LCpCRz58fGYf4zC8KFSLi3f+XkIaomYvJWSAzuGS3PXBaytH51W0JNCZco",
	"dZaGX5ymXwigi9CPJ6Gse6GtO/7F0S+OBlevr/4nAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
