// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
)

// Defines values for UserRole.
const (
	Admin       UserRole = "admin"
	Employee    UserRole = "employee"
	Supervisor  UserRole = "supervisor"
	SystemOwner UserRole = "system_owner"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case Admin:
		return true
	case Employee:
		return true
	case Supervisor:
		return true
	case SystemOwner:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string    `json:"access_token"`
	ExpiresAt   time.Time `json:"expires_at"`
	User        User      `json:"user"`
}

// CompleteRegistrationRequest defines model for CompleteRegistrationRequest.
type CompleteRegistrationRequest struct {
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	StudentGen string `json:"student_gen"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LineLoginRequest defines model for LineLoginRequest.
type LineLoginRequest struct {
	Code        string `json:"code"`
	RedirectUri string `json:"redirect_uri"`
}

// PasswordLoginRequest defines model for PasswordLoginRequest.
type PasswordLoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// User defines model for User.
type User struct {
	DisplayName  *string  `json:"display_name,omitempty"`
	FirstName    *string  `json:"first_name,omitempty"`
	Id           string   `json:"id"`
	IsRegistered bool     `json:"is_registered"`
	LastName     *string  `json:"last_name,omitempty"`
	PictureUrl   *string  `json:"picture_url,omitempty"`
	Role         UserRole `json:"role"`
}

// UserRole defines model for User.Role.
type UserRole string

// LineLoginJSONRequestBody defines body for LineLogin for application/json ContentType.
type LineLoginJSONRequestBody = LineLoginRequest

// PasswordLoginJSONRequestBody defines body for PasswordLogin for application/json ContentType.
type PasswordLoginJSONRequestBody = PasswordLoginRequest

// CompleteRegistrationJSONRequestBody defines body for CompleteRegistration for application/json ContentType.
type CompleteRegistrationJSONRequestBody = CompleteRegistrationRequest

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fhfbhu3E77KgL8f0ASQJaXJQ6A3x0hdF45jyDb6kBoCRY60jHdJhpyVowQCip4hJ+gp0tsEPUkx3JWs",
	"lVZy0NZ56ZvFf/PNN9/M7PijUK7wzqKlKAYfRVQZFjL9eVhSNsTonY3Iv31wHgMZTLtSKYxxRO4GLf+m",
	"uUcxEJGCsVOx6Ah8703AOJLE2xMXCv5LaEl4QKZA0dm+U0YMfPr/ASdiIP7XuwPXq5H1rvjMYtERAd+V",
	"JqAWgzdNNA3b9aPXK2tu/BYVsbUjV/gcCYc4NZGCJOPsEN+VGGnb34kJkUZWFtjqbS737UYqNVoaTVu5",
	"2vBlzdL6u81X2vz5EWVO2QVJKuO2A3G1ju8lO853b7ajsIGmvtZm79RYPHVTs5s05XQ7IQG1CahoVAZz",
	"PyPpmY1LbYDOZYy3Luj9oHx9qiHL1eIOVe4I7QbQ1cnO3YNtQK9qnTeBaRN9LucrGdkyz+WYA0WhxBZg",
	"TU3ee9zo1liYOAopAzB5sToxdi5HabfUfa8dbxSVAUdlyL/qfHB5ehhtWSTJzSNhMXK3FoPoCKkLw0kd",
	"S49hZqLjRSx87uaIa/TuiInhmCYTm65uR4ZTFVUZDM0vuNxUcRmjDBi4HN79+mEpnJ9+vmRs6TSTlnbv",
	"VJQRebHgh42duBRljCoYz8VGDMTL2g+QRGi1tArh8PwEJi7AUYbqRiPClz9++/L505fPvwOVwZ4PX3fh",
	"MjMRokcFJgJlCDGTATUoZylIRTBGukW0ae/YwViqG7QapNVpaYoWgyTUMAnOsmlQuUFL8OevnyAigsZo",
	"prZbVHeOXp9dDk9eXF2enB3zGuPzwTFtB7dGIxueoWWvYvcXDhcZSjVm5cXh+YnoiBmGWLne7z7p9jn+",
	"zqOV3oiBeNrtd5+m5KEsUd+TJWW93Fjs5ZzUKWlcldWcOqlmn2gxuCtGogo/Rnrh9LyqQuxguiO9z41K",
	"t3pvo7N3Le++trNV7BZNobG200LVMBP67/v9f81+oxsn200hJWwQS6UQNeouXCBFkBZYga9tPoeAk4Ax",
	"O0hNEpRzNwbhUVTOowZykLh+DMaC1Nrws7zKYlk6BWOn5xzdRUc86z/ZVvPpydlL4Grd88FNTI6A71Um",
	"7RRhIk2Ourr5dPvmoVKutMRq1igVmRmLs8rIsihkmHOyLB+TkCxVPjNsF8yHxGqyntQpIWJMUuNHaiHt",
	"11CjfzyQjlp71H9eS/1tRbwyMRo7hWVPBa44y6a6S4AndiZzo/dc+rvau6pf7C2fgySmJLVUf9eaFnC7",
	"SYWUd1wijFcokwTaYbTfEUOsVJze6UKNIoIMTI4j/iT1zKcr6cBNDsZchx9xaa6LeU8VuhcRdTL6uMPW",
	"ArIb1gEX79IDWu2dsZSYXs8DV9KeYlrtb0nwWUvKu+m0wrhB2BBn7gYTA6oMgVtLrRqoVBMxzDAcRKNx",
	"DVr1jTHFFlTHSK9QPGBe1KPFVj4c1fjTJLFLeku9ugCmVmE1lVTuNj4uxOBN87PizfXiep28Y6TEHFPC",
	"XVWlVl0uR5+KqprO3WEcVgcu66noH/H24NPfV090LZ9tWxE7w9sG+2BiLFHfF7zOMnQdDmNlUzdlu6ly",
	"R5KwrmwtNbHqRHYDTiOI1ffo7ii2jakP1Jz2TcTfuEftysV1aKBqvPreLrIEDhODuY7fJouXdEIa1JLu",
	"wdmxk0GzjWXr2JXkWZrnP+yrh9XI/5A1sfFPhZZ4XPBMplLXKf1GcpyaGVrmTvEMUN2uqn5M3G12EiVz",
	"0DjD3PmCgXdEGiHTEDXo9XI+kLlIg+f9532xuF78FQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
