// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_audit_logs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminAuditLog = `-- name: CreateAdminAuditLog :one
INSERT INTO admin_audit_logs (actor_id, action, target_type, target_id, reason, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, actor_id, action, target_type, target_id, reason, metadata, created_at
`

type CreateAdminAuditLogParams struct {
	ActorID    pgtype.UUID `json:"actor_id"`
	Action     string      `json:"action"`
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	Reason     pgtype.Text `json:"reason"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error) {
	row := q.db.QueryRow(ctx, createAdminAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.Metadata,
	)
	var i AdminAuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAdminAuditLogsForTarget = `-- name: ListAdminAuditLogsForTarget :many
SELECT id, actor_id, action, target_type, target_id, reason, metadata, created_at FROM admin_audit_logs
WHERE target_type = $1 AND target_id = $2
ORDER BY created_at DESC
`

type ListAdminAuditLogsForTargetParams struct {
	TargetType pgtype.Text `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
}

func (q *Queries) ListAdminAuditLogsForTarget(ctx context.Context, arg ListAdminAuditLogsForTargetParams) ([]AdminAuditLog, error) {
	rows, err := q.db.Query(ctx, listAdminAuditLogsForTarget, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAuditLog
	for rows.Next() {
		var i AdminAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
