// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance_records.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const autoCloseAttendanceRecord = `-- name: AutoCloseAttendanceRecord :one
UPDATE attendance_records
SET check_out_at = $2, auto_closed = true, updated_at = now()
WHERE id = $1
RETURNING id, employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, check_out_at, status, auto_closed, created_at, updated_at
`

type AutoCloseAttendanceRecordParams struct {
	ID         pgtype.UUID        `json:"id"`
	CheckOutAt pgtype.Timestamptz `json:"check_out_at"`
}

func (q *Queries) AutoCloseAttendanceRecord(ctx context.Context, arg AutoCloseAttendanceRecordParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, autoCloseAttendanceRecord, arg.ID, arg.CheckOutAt)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracyM,
		&i.CheckOutAt,
		&i.Status,
		&i.AutoClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttendanceCorrection = `-- name: CreateAttendanceCorrection :one
INSERT INTO attendance_corrections (attendance_record_id, corrected_by, field_name, old_value, new_value, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, attendance_record_id, corrected_by, field_name, old_value, new_value, reason, created_at
`

type CreateAttendanceCorrectionParams struct {
	AttendanceRecordID pgtype.UUID `json:"attendance_record_id"`
	CorrectedBy        pgtype.UUID `json:"corrected_by"`
	FieldName          string      `json:"field_name"`
	OldValue           pgtype.Text `json:"old_value"`
	NewValue           pgtype.Text `json:"new_value"`
	Reason             pgtype.Text `json:"reason"`
}

func (q *Queries) CreateAttendanceCorrection(ctx context.Context, arg CreateAttendanceCorrectionParams) (AttendanceCorrection, error) {
	row := q.db.QueryRow(ctx, createAttendanceCorrection,
		arg.AttendanceRecordID,
		arg.CorrectedBy,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
		arg.Reason,
	)
	var i AttendanceCorrection
	err := row.Scan(
		&i.ID,
		&i.AttendanceRecordID,
		&i.CorrectedBy,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const createCheckIn = `-- name: CreateCheckIn :one
INSERT INTO attendance_records
    (employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, check_out_at, status, auto_closed, created_at, updated_at
`

type CreateCheckInParams struct {
	EmployeeID       pgtype.UUID          `json:"employee_id"`
	WorkDate         pgtype.Date          `json:"work_date"`
	CheckInAt        pgtype.Timestamptz   `json:"check_in_at"`
	CheckInLat       pgtype.Float8        `json:"check_in_lat"`
	CheckInLng       pgtype.Float8        `json:"check_in_lng"`
	CheckInAccuracyM pgtype.Float8        `json:"check_in_accuracy_m"`
	Status           NullAttendanceStatus `json:"status"`
}

func (q *Queries) CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, createCheckIn,
		arg.EmployeeID,
		arg.WorkDate,
		arg.CheckInAt,
		arg.CheckInLat,
		arg.CheckInLng,
		arg.CheckInAccuracyM,
		arg.Status,
	)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracyM,
		&i.CheckOutAt,
		&i.Status,
		&i.AutoClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttendanceRecordByEmployeeAndDate = `-- name: GetAttendanceRecordByEmployeeAndDate :one
SELECT id, employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, check_out_at, status, auto_closed, created_at, updated_at FROM attendance_records
WHERE employee_id = $1 AND work_date = $2
`

type GetAttendanceRecordByEmployeeAndDateParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	WorkDate   pgtype.Date `json:"work_date"`
}

func (q *Queries) GetAttendanceRecordByEmployeeAndDate(ctx context.Context, arg GetAttendanceRecordByEmployeeAndDateParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, getAttendanceRecordByEmployeeAndDate, arg.EmployeeID, arg.WorkDate)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracyM,
		&i.CheckOutAt,
		&i.Status,
		&i.AutoClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAttendanceCorrectionsForRecord = `-- name: ListAttendanceCorrectionsForRecord :many
SELECT id, attendance_record_id, corrected_by, field_name, old_value, new_value, reason, created_at FROM attendance_corrections
WHERE attendance_record_id = $1
ORDER BY created_at
`

func (q *Queries) ListAttendanceCorrectionsForRecord(ctx context.Context, attendanceRecordID pgtype.UUID) ([]AttendanceCorrection, error) {
	rows, err := q.db.Query(ctx, listAttendanceCorrectionsForRecord, attendanceRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceCorrection
	for rows.Next() {
		var i AttendanceCorrection
		if err := rows.Scan(
			&i.ID,
			&i.AttendanceRecordID,
			&i.CorrectedBy,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAttendanceRecordsBeforeDate = `-- name: ListOpenAttendanceRecordsBeforeDate :many
SELECT id, employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, check_out_at, status, auto_closed, created_at, updated_at FROM attendance_records
WHERE check_out_at IS NULL AND work_date < $1
`

// Used by the end-of-day auto-close job.
func (q *Queries) ListOpenAttendanceRecordsBeforeDate(ctx context.Context, workDate pgtype.Date) ([]AttendanceRecord, error) {
	rows, err := q.db.Query(ctx, listOpenAttendanceRecordsBeforeDate, workDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttendanceRecord
	for rows.Next() {
		var i AttendanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.WorkDate,
			&i.CheckInAt,
			&i.CheckInLat,
			&i.CheckInLng,
			&i.CheckInAccuracyM,
			&i.CheckOutAt,
			&i.Status,
			&i.AutoClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCheckOut = `-- name: SetCheckOut :one
UPDATE attendance_records
SET check_out_at = $2, updated_at = now()
WHERE id = $1
RETURNING id, employee_id, work_date, check_in_at, check_in_lat, check_in_lng, check_in_accuracy_m, check_out_at, status, auto_closed, created_at, updated_at
`

type SetCheckOutParams struct {
	ID         pgtype.UUID        `json:"id"`
	CheckOutAt pgtype.Timestamptz `json:"check_out_at"`
}

func (q *Queries) SetCheckOut(ctx context.Context, arg SetCheckOutParams) (AttendanceRecord, error) {
	row := q.db.QueryRow(ctx, setCheckOut, arg.ID, arg.CheckOutAt)
	var i AttendanceRecord
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.WorkDate,
		&i.CheckInAt,
		&i.CheckInLat,
		&i.CheckInLng,
		&i.CheckInAccuracyM,
		&i.CheckOutAt,
		&i.Status,
		&i.AutoClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
