// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: holidays.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateManualHoliday = `-- name: CreateOrUpdateManualHoliday :one
INSERT INTO holidays (date, name, local_name, source, updated_by)
VALUES ($1, $2, $3, 'manual', $4)
ON CONFLICT (date) DO UPDATE
SET name = EXCLUDED.name, local_name = EXCLUDED.local_name,
    source = 'manual', updated_by = EXCLUDED.updated_by, updated_at = now()
RETURNING id, date, name, local_name, source, updated_by, created_at, updated_at
`

type CreateOrUpdateManualHolidayParams struct {
	Date      pgtype.Date `json:"date"`
	Name      string      `json:"name"`
	LocalName pgtype.Text `json:"local_name"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

func (q *Queries) CreateOrUpdateManualHoliday(ctx context.Context, arg CreateOrUpdateManualHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createOrUpdateManualHoliday,
		arg.Date,
		arg.Name,
		arg.LocalName,
		arg.UpdatedBy,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Name,
		&i.LocalName,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1
`

func (q *Queries) DeleteHoliday(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteHoliday, id)
	return err
}

const getHolidayByDate = `-- name: GetHolidayByDate :one
SELECT id, date, name, local_name, source, updated_by, created_at, updated_at FROM holidays WHERE date = $1
`

func (q *Queries) GetHolidayByDate(ctx context.Context, date pgtype.Date) (Holiday, error) {
	row := q.db.QueryRow(ctx, getHolidayByDate, date)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Name,
		&i.LocalName,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHolidaysInRange = `-- name: ListHolidaysInRange :many
SELECT id, date, name, local_name, source, updated_by, created_at, updated_at FROM holidays
WHERE date BETWEEN $1 AND $2
ORDER BY date
`

type ListHolidaysInRangeParams struct {
	Date   pgtype.Date `json:"date"`
	Date_2 pgtype.Date `json:"date_2"`
}

func (q *Queries) ListHolidaysInRange(ctx context.Context, arg ListHolidaysInRangeParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidaysInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Holiday
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.Name,
			&i.LocalName,
			&i.Source,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncedHoliday = `-- name: UpsertSyncedHoliday :one
INSERT INTO holidays (date, name, local_name, source)
VALUES ($1, $2, $3, 'nager_date')
ON CONFLICT (date) DO UPDATE
SET name = EXCLUDED.name, local_name = EXCLUDED.local_name, updated_at = now()
WHERE holidays.updated_by IS NULL
RETURNING id, date, name, local_name, source, updated_by, created_at, updated_at
`

type UpsertSyncedHolidayParams struct {
	Date      pgtype.Date `json:"date"`
	Name      string      `json:"name"`
	LocalName pgtype.Text `json:"local_name"`
}

// Used by the Nager.Date sync job. ON CONFLICT only touches name/local_name
// so a manual edit (source='manual' or a later updated_at) isn't clobbered
// by a re-sync — callers should check updated_by before overwriting.
func (q *Queries) UpsertSyncedHoliday(ctx context.Context, arg UpsertSyncedHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, upsertSyncedHoliday, arg.Date, arg.Name, arg.LocalName)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.Name,
		&i.LocalName,
		&i.Source,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
