// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leave_requests.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLeaveRequest = `-- name: CreateLeaveRequest :one
INSERT INTO leave_requests
    (employee_id, start_date, end_date, reason, approval_token_hash, approval_token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at
`

type CreateLeaveRequestParams struct {
	EmployeeID             pgtype.UUID        `json:"employee_id"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	Reason                 pgtype.Text        `json:"reason"`
	ApprovalTokenHash      pgtype.Text        `json:"approval_token_hash"`
	ApprovalTokenExpiresAt pgtype.Timestamptz `json:"approval_token_expires_at"`
}

func (q *Queries) CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, createLeaveRequest,
		arg.EmployeeID,
		arg.StartDate,
		arg.EndDate,
		arg.Reason,
		arg.ApprovalTokenHash,
		arg.ApprovalTokenExpiresAt,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.Status,
		&i.ApprovalTokenHash,
		&i.ApprovalTokenExpiresAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecidedFromIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const decideLeaveRequest = `-- name: DecideLeaveRequest :one
UPDATE leave_requests
SET status = $2, decided_by = $3, decided_at = now(), decided_from_ip = $4,
    approval_token_hash = NULL, updated_at = now()
WHERE id = $1
RETURNING id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at
`

type DecideLeaveRequestParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        LeaveStatus `json:"status"`
	DecidedBy     pgtype.UUID `json:"decided_by"`
	DecidedFromIp pgtype.Text `json:"decided_from_ip"`
}

func (q *Queries) DecideLeaveRequest(ctx context.Context, arg DecideLeaveRequestParams) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, decideLeaveRequest,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.DecidedFromIp,
	)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.Status,
		&i.ApprovalTokenHash,
		&i.ApprovalTokenExpiresAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecidedFromIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveRequestByApprovalTokenHash = `-- name: GetLeaveRequestByApprovalTokenHash :one
SELECT id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at FROM leave_requests
WHERE approval_token_hash = $1
  AND status = 'pending'
  AND approval_token_expires_at > now()
`

func (q *Queries) GetLeaveRequestByApprovalTokenHash(ctx context.Context, approvalTokenHash pgtype.Text) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestByApprovalTokenHash, approvalTokenHash)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.Status,
		&i.ApprovalTokenHash,
		&i.ApprovalTokenExpiresAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecidedFromIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaveRequestByID = `-- name: GetLeaveRequestByID :one
SELECT id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at FROM leave_requests WHERE id = $1
`

func (q *Queries) GetLeaveRequestByID(ctx context.Context, id pgtype.UUID) (LeaveRequest, error) {
	row := q.db.QueryRow(ctx, getLeaveRequestByID, id)
	var i LeaveRequest
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StartDate,
		&i.EndDate,
		&i.Reason,
		&i.Status,
		&i.ApprovalTokenHash,
		&i.ApprovalTokenExpiresAt,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.DecidedFromIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLeaveRequestsForEmployee = `-- name: ListLeaveRequestsForEmployee :many
SELECT id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at FROM leave_requests
WHERE employee_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLeaveRequestsForEmployee(ctx context.Context, employeeID pgtype.UUID) ([]LeaveRequest, error) {
	rows, err := q.db.Query(ctx, listLeaveRequestsForEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.Status,
			&i.ApprovalTokenHash,
			&i.ApprovalTokenExpiresAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecidedFromIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLeaveRequestsOlderThan = `-- name: ListPendingLeaveRequestsOlderThan :many
SELECT id, employee_id, start_date, end_date, reason, status, approval_token_hash, approval_token_expires_at, decided_by, decided_at, decided_from_ip, created_at, updated_at FROM leave_requests
WHERE status = 'pending' AND created_at < $1
`

// Used by the reminder/escalation job.
func (q *Queries) ListPendingLeaveRequestsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]LeaveRequest, error) {
	rows, err := q.db.Query(ctx, listPendingLeaveRequestsOlderThan, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaveRequest
	for rows.Next() {
		var i LeaveRequest
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.Reason,
			&i.Status,
			&i.ApprovalTokenHash,
			&i.ApprovalTokenExpiresAt,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.DecidedFromIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
