// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AttendanceStatus string

const (
	AttendanceStatusPresent AttendanceStatus = "present"
	AttendanceStatusValue1  AttendanceStatus = "สาย"
	AttendanceStatusValue2  AttendanceStatus = "ขาด"
)

func (e *AttendanceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AttendanceStatus(s)
	case string:
		*e = AttendanceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AttendanceStatus: %T", src)
	}
	return nil
}

type NullAttendanceStatus struct {
	AttendanceStatus AttendanceStatus `json:"attendance_status"`
	Valid            bool             `json:"valid"` // Valid is true if AttendanceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAttendanceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AttendanceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AttendanceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAttendanceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AttendanceStatus), nil
}

type HolidaySource string

const (
	HolidaySourceNagerDate HolidaySource = "nager_date"
	HolidaySourceManual    HolidaySource = "manual"
)

func (e *HolidaySource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HolidaySource(s)
	case string:
		*e = HolidaySource(s)
	default:
		return fmt.Errorf("unsupported scan type for HolidaySource: %T", src)
	}
	return nil
}

type NullHolidaySource struct {
	HolidaySource HolidaySource `json:"holiday_source"`
	Valid         bool          `json:"valid"` // Valid is true if HolidaySource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHolidaySource) Scan(value interface{}) error {
	if value == nil {
		ns.HolidaySource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HolidaySource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHolidaySource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HolidaySource), nil
}

type LeaveStatus string

const (
	LeaveStatusPending  LeaveStatus = "pending"
	LeaveStatusApproved LeaveStatus = "approved"
	LeaveStatusRejected LeaveStatus = "rejected"
)

func (e *LeaveStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaveStatus(s)
	case string:
		*e = LeaveStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaveStatus: %T", src)
	}
	return nil
}

type NullLeaveStatus struct {
	LeaveStatus LeaveStatus `json:"leave_status"`
	Valid       bool        `json:"valid"` // Valid is true if LeaveStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaveStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeaveStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaveStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaveStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaveStatus), nil
}

type UserRole string

const (
	UserRoleSystemOwner UserRole = "system_owner"
	UserRoleAdmin       UserRole = "admin"
	UserRoleSupervisor  UserRole = "supervisor"
	UserRoleEmployee    UserRole = "employee"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusActive   UserStatus = "active"
	UserStatusInactive UserStatus = "inactive"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AdminAuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType pgtype.Text        `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Reason     pgtype.Text        `json:"reason"`
	Metadata   []byte             `json:"metadata"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AttendanceCorrection struct {
	ID                 pgtype.UUID        `json:"id"`
	AttendanceRecordID pgtype.UUID        `json:"attendance_record_id"`
	CorrectedBy        pgtype.UUID        `json:"corrected_by"`
	FieldName          string             `json:"field_name"`
	OldValue           pgtype.Text        `json:"old_value"`
	NewValue           pgtype.Text        `json:"new_value"`
	Reason             pgtype.Text        `json:"reason"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type AttendanceRecord struct {
	ID               pgtype.UUID          `json:"id"`
	EmployeeID       pgtype.UUID          `json:"employee_id"`
	WorkDate         pgtype.Date          `json:"work_date"`
	CheckInAt        pgtype.Timestamptz   `json:"check_in_at"`
	CheckInLat       pgtype.Float8        `json:"check_in_lat"`
	CheckInLng       pgtype.Float8        `json:"check_in_lng"`
	CheckInAccuracyM pgtype.Float8        `json:"check_in_accuracy_m"`
	CheckOutAt       pgtype.Timestamptz   `json:"check_out_at"`
	Status           NullAttendanceStatus `json:"status"`
	AutoClosed       bool                 `json:"auto_closed"`
	CreatedAt        pgtype.Timestamptz   `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz   `json:"updated_at"`
}

type Holiday struct {
	ID        pgtype.UUID        `json:"id"`
	Date      pgtype.Date        `json:"date"`
	Name      string             `json:"name"`
	LocalName pgtype.Text        `json:"local_name"`
	Source    HolidaySource      `json:"source"`
	UpdatedBy pgtype.UUID        `json:"updated_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LeaveRequest struct {
	ID                     pgtype.UUID        `json:"id"`
	EmployeeID             pgtype.UUID        `json:"employee_id"`
	StartDate              pgtype.Date        `json:"start_date"`
	EndDate                pgtype.Date        `json:"end_date"`
	Reason                 pgtype.Text        `json:"reason"`
	Status                 LeaveStatus        `json:"status"`
	ApprovalTokenHash      pgtype.Text        `json:"approval_token_hash"`
	ApprovalTokenExpiresAt pgtype.Timestamptz `json:"approval_token_expires_at"`
	DecidedBy              pgtype.UUID        `json:"decided_by"`
	DecidedAt              pgtype.Timestamptz `json:"decided_at"`
	DecidedFromIp          pgtype.Text        `json:"decided_from_ip"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UserAgent pgtype.Text        `json:"user_agent"`
	IpAddress pgtype.Text        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Team struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                      pgtype.UUID        `json:"id"`
	Role                    UserRole           `json:"role"`
	Status                  UserStatus         `json:"status"`
	TeamID                  pgtype.UUID        `json:"team_id"`
	LineUserID              pgtype.Text        `json:"line_user_id"`
	LineDisplayName         pgtype.Text        `json:"line_display_name"`
	LinePictureUrl          pgtype.Text        `json:"line_picture_url"`
	Username                pgtype.Text        `json:"username"`
	PasswordHash            pgtype.Text        `json:"password_hash"`
	FirstName               pgtype.Text        `json:"first_name"`
	LastName                pgtype.Text        `json:"last_name"`
	StudentGen              pgtype.Text        `json:"student_gen"`
	RegistrationCompletedAt pgtype.Timestamptz `json:"registration_completed_at"`
	OffboardedAt            pgtype.Timestamptz `json:"offboarded_at"`
	OffboardedBy            pgtype.UUID        `json:"offboarded_by"`
	OffboardedReason        pgtype.Text        `json:"offboarded_reason"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type WorkSchedule struct {
	ID            pgtype.UUID        `json:"id"`
	EmployeeID    pgtype.UUID        `json:"employee_id"`
	DayOfWeek     int16              `json:"day_of_week"`
	StartTime     pgtype.Time        `json:"start_time"`
	EndTime       pgtype.Time        `json:"end_time"`
	EffectiveFrom pgtype.Date        `json:"effective_from"`
	EffectiveTo   pgtype.Date        `json:"effective_to"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
