// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AutoCloseAttendanceRecord(ctx context.Context, arg AutoCloseAttendanceRecordParams) (AttendanceRecord, error)
	CompleteRegistration(ctx context.Context, arg CompleteRegistrationParams) (User, error)
	CreateAdminAuditLog(ctx context.Context, arg CreateAdminAuditLogParams) (AdminAuditLog, error)
	CreateAttendanceCorrection(ctx context.Context, arg CreateAttendanceCorrectionParams) (AttendanceCorrection, error)
	CreateCheckIn(ctx context.Context, arg CreateCheckInParams) (AttendanceRecord, error)
	// First-time LINE login always creates an 'employee' — promotion to
	// admin/supervisor is done by the system_owner afterwards.
	CreateEmployeeFromLine(ctx context.Context, arg CreateEmployeeFromLineParams) (User, error)
	CreateLeaveRequest(ctx context.Context, arg CreateLeaveRequestParams) (LeaveRequest, error)
	CreateOrUpdateManualHoliday(ctx context.Context, arg CreateOrUpdateManualHolidayParams) (Holiday, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateSystemOwner(ctx context.Context, arg CreateSystemOwnerParams) (User, error)
	CreateWorkSchedule(ctx context.Context, arg CreateWorkScheduleParams) (WorkSchedule, error)
	DecideLeaveRequest(ctx context.Context, arg DecideLeaveRequestParams) (LeaveRequest, error)
	DeleteHoliday(ctx context.Context, id pgtype.UUID) error
	DeleteWorkSchedule(ctx context.Context, id pgtype.UUID) error
	GetActiveRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetAttendanceRecordByEmployeeAndDate(ctx context.Context, arg GetAttendanceRecordByEmployeeAndDateParams) (AttendanceRecord, error)
	GetHolidayByDate(ctx context.Context, date pgtype.Date) (Holiday, error)
	GetLeaveRequestByApprovalTokenHash(ctx context.Context, approvalTokenHash pgtype.Text) (LeaveRequest, error)
	GetLeaveRequestByID(ctx context.Context, id pgtype.UUID) (LeaveRequest, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByLineUserID(ctx context.Context, lineUserID pgtype.Text) (User, error)
	GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error)
	ListAdminAuditLogsForTarget(ctx context.Context, arg ListAdminAuditLogsForTargetParams) ([]AdminAuditLog, error)
	ListAttendanceCorrectionsForRecord(ctx context.Context, attendanceRecordID pgtype.UUID) ([]AttendanceCorrection, error)
	ListHolidaysInRange(ctx context.Context, arg ListHolidaysInRangeParams) ([]Holiday, error)
	ListLeaveRequestsForEmployee(ctx context.Context, employeeID pgtype.UUID) ([]LeaveRequest, error)
	// Used by the end-of-day auto-close job.
	ListOpenAttendanceRecordsBeforeDate(ctx context.Context, workDate pgtype.Date) ([]AttendanceRecord, error)
	// Used by the reminder/escalation job.
	ListPendingLeaveRequestsOlderThan(ctx context.Context, createdAt pgtype.Timestamptz) ([]LeaveRequest, error)
	ListWorkSchedulesForEmployee(ctx context.Context, employeeID pgtype.UUID) ([]WorkSchedule, error)
	RevokeAllRefreshTokensForUser(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetCheckOut(ctx context.Context, arg SetCheckOutParams) (AttendanceRecord, error)
	UpdateLineProfile(ctx context.Context, arg UpdateLineProfileParams) error
	// Used by the Nager.Date sync job. ON CONFLICT only touches name/local_name
	// so a manual edit (source='manual' or a later updated_at) isn't clobbered
	// by a re-sync — callers should check updated_by before overwriting.
	UpsertSyncedHoliday(ctx context.Context, arg UpsertSyncedHolidayParams) (Holiday, error)
}

var _ Querier = (*Queries)(nil)
