// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeRegistration = `-- name: CompleteRegistration :one
UPDATE users
SET first_name = $2,
    last_name = $3,
    student_gen = $4,
    registration_completed_at = now(),
    updated_at = now()
WHERE id = $1
RETURNING id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at
`

type CompleteRegistrationParams struct {
	ID         pgtype.UUID `json:"id"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	StudentGen pgtype.Text `json:"student_gen"`
}

func (q *Queries) CompleteRegistration(ctx context.Context, arg CompleteRegistrationParams) (User, error) {
	row := q.db.QueryRow(ctx, completeRegistration,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.StudentGen,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmployeeFromLine = `-- name: CreateEmployeeFromLine :one
INSERT INTO users (role, line_user_id, line_display_name, line_picture_url)
VALUES ('employee', $1, $2, $3)
RETURNING id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at
`

type CreateEmployeeFromLineParams struct {
	LineUserID      pgtype.Text `json:"line_user_id"`
	LineDisplayName pgtype.Text `json:"line_display_name"`
	LinePictureUrl  pgtype.Text `json:"line_picture_url"`
}

// First-time LINE login always creates an 'employee' — promotion to
// admin/supervisor is done by the system_owner afterwards.
func (q *Queries) CreateEmployeeFromLine(ctx context.Context, arg CreateEmployeeFromLineParams) (User, error) {
	row := q.db.QueryRow(ctx, createEmployeeFromLine, arg.LineUserID, arg.LineDisplayName, arg.LinePictureUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSystemOwner = `-- name: CreateSystemOwner :one
INSERT INTO users (role, username, password_hash)
VALUES ('system_owner', $1, $2)
RETURNING id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at
`

type CreateSystemOwnerParams struct {
	Username     pgtype.Text `json:"username"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreateSystemOwner(ctx context.Context, arg CreateSystemOwnerParams) (User, error) {
	row := q.db.QueryRow(ctx, createSystemOwner, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByLineUserID = `-- name: GetUserByLineUserID :one
SELECT id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at FROM users WHERE line_user_id = $1
`

func (q *Queries) GetUserByLineUserID(ctx context.Context, lineUserID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLineUserID, lineUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, status, team_id, line_user_id, line_display_name, line_picture_url, username, password_hash, first_name, last_name, student_gen, registration_completed_at, offboarded_at, offboarded_by, offboarded_reason, created_at, updated_at FROM users WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Status,
		&i.TeamID,
		&i.LineUserID,
		&i.LineDisplayName,
		&i.LinePictureUrl,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.StudentGen,
		&i.RegistrationCompletedAt,
		&i.OffboardedAt,
		&i.OffboardedBy,
		&i.OffboardedReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLineProfile = `-- name: UpdateLineProfile :exec
UPDATE users
SET line_display_name = $2, line_picture_url = $3, updated_at = now()
WHERE id = $1
`

type UpdateLineProfileParams struct {
	ID              pgtype.UUID `json:"id"`
	LineDisplayName pgtype.Text `json:"line_display_name"`
	LinePictureUrl  pgtype.Text `json:"line_picture_url"`
}

func (q *Queries) UpdateLineProfile(ctx context.Context, arg UpdateLineProfileParams) error {
	_, err := q.db.Exec(ctx, updateLineProfile, arg.ID, arg.LineDisplayName, arg.LinePictureUrl)
	return err
}
