// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_schedules.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkSchedule = `-- name: CreateWorkSchedule :one
INSERT INTO work_schedules (employee_id, day_of_week, start_time, end_time, effective_from, effective_to)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, employee_id, day_of_week, start_time, end_time, effective_from, effective_to, created_at, updated_at
`

type CreateWorkScheduleParams struct {
	EmployeeID    pgtype.UUID `json:"employee_id"`
	DayOfWeek     int16       `json:"day_of_week"`
	StartTime     pgtype.Time `json:"start_time"`
	EndTime       pgtype.Time `json:"end_time"`
	EffectiveFrom pgtype.Date `json:"effective_from"`
	EffectiveTo   pgtype.Date `json:"effective_to"`
}

func (q *Queries) CreateWorkSchedule(ctx context.Context, arg CreateWorkScheduleParams) (WorkSchedule, error) {
	row := q.db.QueryRow(ctx, createWorkSchedule,
		arg.EmployeeID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkSchedule = `-- name: DeleteWorkSchedule :exec
DELETE FROM work_schedules WHERE id = $1
`

func (q *Queries) DeleteWorkSchedule(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkSchedule, id)
	return err
}

const listWorkSchedulesForEmployee = `-- name: ListWorkSchedulesForEmployee :many
SELECT id, employee_id, day_of_week, start_time, end_time, effective_from, effective_to, created_at, updated_at FROM work_schedules
WHERE employee_id = $1
ORDER BY day_of_week, start_time
`

func (q *Queries) ListWorkSchedulesForEmployee(ctx context.Context, employeeID pgtype.UUID) ([]WorkSchedule, error) {
	rows, err := q.db.Query(ctx, listWorkSchedulesForEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkSchedule
	for rows.Next() {
		var i WorkSchedule
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
