//go:build !wireinject

// Code generated by Wire. Hand-maintained for now — this mirrors what
// `wire.go` describes. Regenerate with `make wire` once the graph grows
// further, then delete this notice.
package wire

import (
	"log/slog"

	"checkdee-backend/internal/config"
	"checkdee-backend/internal/db"
	"checkdee-backend/internal/handler"
	"checkdee-backend/internal/lineclient"
	"checkdee-backend/internal/repository"
	"checkdee-backend/internal/server"
	"checkdee-backend/internal/usecase"
)

func InitializeServer(logger *slog.Logger) (*server.Server, error) {
	cfg, err := config.Load()
	if err != nil {
		return nil, err
	}

	pool, err := db.Connect(cfg.DatabaseURL)
	if err != nil {
		return nil, err
	}

	userRepo := repository.NewUserRepository(pool)
	refreshTokenRepo := repository.NewRefreshTokenRepository(pool)
	lineClient := lineclient.New(cfg.LineChannelID, cfg.LineChannelSecret)
	jwtIssuer := usecase.NewJWTIssuer(cfg.JWTSecret)

	authUsecase := usecase.NewAuthUsecase(userRepo, refreshTokenRepo, lineClient, jwtIssuer)
	authHandler := handler.NewAuthHandler(authUsecase)

	return server.New(cfg, logger, authHandler, jwtIssuer), nil
}
