// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"checkdee-backend/internal/config"
	"checkdee-backend/internal/db"
	"checkdee-backend/internal/handler"
	"checkdee-backend/internal/jobs"
	"checkdee-backend/internal/lineclient"
	"checkdee-backend/internal/nagerclient"
	"checkdee-backend/internal/qrsign"
	"checkdee-backend/internal/repository"
	"checkdee-backend/internal/server"
	"checkdee-backend/internal/usecase"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/riverqueue/river"
	"log/slog"
	"time"
)

// Injectors from wire.go:

func InitializeServer(logger *slog.Logger) (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	pool, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(pool)
	refreshTokenRepository := repository.NewRefreshTokenRepository(pool)
	client := provideLineClient(configConfig)
	jwtIssuer := provideJWTIssuer(configConfig)
	authUsecase := usecase.NewAuthUsecase(userRepository, refreshTokenRepository, client, jwtIssuer)
	authHandler := handler.NewAuthHandler(authUsecase)
	workScheduleRepository := repository.NewWorkScheduleRepository(pool)
	scheduleUsecase := usecase.NewScheduleUsecase(workScheduleRepository)
	scheduleHandler := handler.NewScheduleHandler(scheduleUsecase)
	holidayRepository := repository.NewHolidayRepository(pool)
	holidayUsecase := usecase.NewHolidayUsecase(holidayRepository)
	holidayHandler := handler.NewHolidayHandler(holidayUsecase)
	kioskDeviceRepository := repository.NewKioskDeviceRepository(pool)
	kioskDeviceUsecase := usecase.NewKioskDeviceUsecase(kioskDeviceRepository)
	attendanceRepository := repository.NewAttendanceRepository(pool)
	qrNonceRepository := repository.NewQRNonceRepository(pool)
	signer := provideQRSigner(configConfig)
	attendanceUsecase := usecase.NewAttendanceUsecase(attendanceRepository, workScheduleRepository, kioskDeviceRepository, qrNonceRepository, signer)
	kioskHandler := handler.NewKioskHandler(kioskDeviceUsecase, attendanceUsecase)
	attendanceHandler := handler.NewAttendanceHandler(attendanceUsecase)
	nagerclientClient := provideNagerClient()
	holidaySyncWorker := jobs.NewHolidaySyncWorker(nagerclientClient, holidayRepository)
	attendanceAutoCloseWorker := jobs.NewAttendanceAutoCloseWorker(attendanceRepository)
	workers := provideRiverWorkers(holidaySyncWorker, attendanceAutoCloseWorker)
	v := providePeriodicJobs()
	riverClient, err := jobs.NewClient(pool, workers, v)
	if err != nil {
		return nil, err
	}
	serverServer := server.New(configConfig, logger, authHandler, scheduleHandler, holidayHandler, kioskHandler, attendanceHandler, jwtIssuer, kioskDeviceUsecase, riverClient)
	return serverServer, nil
}

// wire.go:

// provideDB connects the server's own pool through the least-privilege
// checkdee_app role, not the owner/superuser DatabaseURL — see AppDatabaseURL
// on config.Config.
func provideDB(cfg *config.Config) (*pgxpool.Pool, error) {
	return db.Connect(cfg.AppDatabaseURL)
}

func provideLineClient(cfg *config.Config) *lineclient.Client {
	return lineclient.New(cfg.LineChannelID, cfg.LineChannelSecret)
}

func provideJWTIssuer(cfg *config.Config) *usecase.JWTIssuer {
	return usecase.NewJWTIssuer(cfg.JWTSecret)
}

func provideNagerClient() *nagerclient.Client {
	return nagerclient.New()
}

func provideQRSigner(cfg *config.Config) *qrsign.Signer {
	return qrsign.NewSigner(cfg.QRSigningSecret)
}

// provideRiverWorkers registers every worker this process runs.
func provideRiverWorkers(holidaySyncWorker *jobs.HolidaySyncWorker, attendanceAutoCloseWorker *jobs.AttendanceAutoCloseWorker) *river.Workers {
	workers := jobs.Workers()
	river.AddWorker(workers, holidaySyncWorker)
	river.AddWorker(workers, attendanceAutoCloseWorker)
	return workers
}

// providePeriodicJobs schedules holiday sync (daily, current year,
// UpsertSynced's "manual edits win" guard makes re-runs safe, RunOnStart so
// a fresh deploy doesn't wait a day) and attendance auto-close (hourly —
// cheap no-op once a day's stragglers are closed, since the underlying
// UPDATE only ever touches rows still missing a checkout).
func providePeriodicJobs() []*river.PeriodicJob {
	return []*river.PeriodicJob{river.NewPeriodicJob(river.PeriodicInterval(24*time.Hour), func() (river.JobArgs, *river.InsertOpts) {
		return jobs.HolidaySyncArgs{Year: time.Now().Year()}, nil
	},
		&river.PeriodicJobOpts{RunOnStart: true},
	), river.NewPeriodicJob(river.PeriodicInterval(1*time.Hour), func() (river.JobArgs, *river.InsertOpts) {
		return jobs.AttendanceAutoCloseArgs{}, nil
	},
		&river.PeriodicJobOpts{RunOnStart: true},
	),
	}
}
