// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"checkdee-backend/internal/config"
	"checkdee-backend/internal/db"
	"checkdee-backend/internal/domain"
	"checkdee-backend/internal/handler"
	"checkdee-backend/internal/jobs"
	"checkdee-backend/internal/lineclient"
	"checkdee-backend/internal/nagerclient"
	"checkdee-backend/internal/qrsign"
	"checkdee-backend/internal/repository"
	"checkdee-backend/internal/server"
	"checkdee-backend/internal/usecase"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/riverqueue/river"
	"log/slog"
	"time"
)

// Injectors from wire.go:

func InitializeServer(logger *slog.Logger) (*server.Server, error) {
	configConfig, err := config.Load()
	if err != nil {
		return nil, err
	}
	pool, err := provideDB(configConfig)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(pool)
	refreshTokenRepository := repository.NewRefreshTokenRepository(pool)
	client := provideLineClient(configConfig)
	jwtIssuer := provideJWTIssuer(configConfig)
	authUsecase := usecase.NewAuthUsecase(userRepository, refreshTokenRepository, client, jwtIssuer)
	authHandler := handler.NewAuthHandler(authUsecase)
	workScheduleRepository := repository.NewWorkScheduleRepository(pool)
	scheduleUsecase := usecase.NewScheduleUsecase(workScheduleRepository)
	scheduleHandler := handler.NewScheduleHandler(scheduleUsecase)
	holidayRepository := repository.NewHolidayRepository(pool)
	holidayUsecase := usecase.NewHolidayUsecase(holidayRepository)
	holidayHandler := handler.NewHolidayHandler(holidayUsecase)
	kioskDeviceRepository := repository.NewKioskDeviceRepository(pool)
	kioskDeviceUsecase := usecase.NewKioskDeviceUsecase(kioskDeviceRepository)
	attendanceRepository := repository.NewAttendanceRepository(pool)
	qrNonceRepository := repository.NewQRNonceRepository(pool)
	signer := provideQRSigner(configConfig)
	attendanceUsecase := usecase.NewAttendanceUsecase(attendanceRepository, workScheduleRepository, kioskDeviceRepository, qrNonceRepository, signer)
	kioskHandler := handler.NewKioskHandler(kioskDeviceUsecase, attendanceUsecase)
	attendanceHandler := handler.NewAttendanceHandler(attendanceUsecase)
	reportRepository := repository.NewReportRepository(pool)
	reportUsecase := usecase.NewReportUsecase(userRepository, attendanceRepository, workScheduleRepository, reportRepository)
	reportExportRepository := repository.NewReportExportRepository(pool)
	nagerclientClient := provideNagerClient()
	holidaySyncWorker := jobs.NewHolidaySyncWorker(nagerclientClient, holidayRepository)
	attendanceAutoCloseWorker := jobs.NewAttendanceAutoCloseWorker(attendanceRepository)
	reportExportWorker := provideReportExportWorker(reportExportRepository, reportUsecase)
	workers := provideRiverWorkers(holidaySyncWorker, attendanceAutoCloseWorker, reportExportWorker)
	v := providePeriodicJobs()
	riverClient, err := jobs.NewClient(pool, workers, v)
	if err != nil {
		return nil, err
	}
	reportExportRiverClient := provideReportExportRiverClient(riverClient)
	reportExportUsecase := usecase.NewReportExportUsecase(reportExportRepository, reportExportRiverClient)
	reportHandler := handler.NewReportHandler(reportUsecase, reportExportUsecase)
	leaveRequestRepository := repository.NewLeaveRequestRepository(pool)
	auditLogRepository := repository.NewAuditLogRepository(pool)
	auditLogUsecase := usecase.NewAuditLogUsecase(auditLogRepository)
	leaveUsecase := usecase.NewLeaveUsecase(leaveRequestRepository, auditLogUsecase)
	leaveHandler := handler.NewLeaveHandler(leaveUsecase)
	serverServer := server.New(configConfig, logger, authHandler, scheduleHandler, holidayHandler, kioskHandler, attendanceHandler, reportHandler, leaveHandler, jwtIssuer, kioskDeviceUsecase, riverClient)
	return serverServer, nil
}

// wire.go:

// provideDB connects the server's own pool through the least-privilege
// checkdee_app role, not the owner/superuser DatabaseURL — see AppDatabaseURL
// on config.Config.
func provideDB(cfg *config.Config) (*pgxpool.Pool, error) {
	return db.Connect(cfg.AppDatabaseURL)
}

func provideLineClient(cfg *config.Config) *lineclient.Client {
	return lineclient.New(cfg.LineChannelID, cfg.LineChannelSecret)
}

func provideJWTIssuer(cfg *config.Config) *usecase.JWTIssuer {
	return usecase.NewJWTIssuer(cfg.JWTSecret)
}

func provideNagerClient() *nagerclient.Client {
	return nagerclient.New()
}

func provideQRSigner(cfg *config.Config) *qrsign.Signer {
	return qrsign.NewSigner(cfg.QRSigningSecret)
}

// provideReportExportRiverClient adapts the concrete river client to the
// small interface usecase.ReportExportUsecase depends on, so that package
// doesn't need to know about river's generic Client[TTx] type.
func provideReportExportRiverClient(riverClient *river.Client[pgx.Tx]) usecase.ReportExportRiverClient {
	return riverClient
}

// provideReportExportWorker wraps the report usecase's query methods as
// closures rather than the worker depending on *usecase.ReportUsecase
// directly — see ReportExportWorker's doc comment for why (avoids an
// import cycle between usecase and jobs).
func provideReportExportWorker(exports domain.ReportExportRepository, reports *usecase.ReportUsecase) *jobs.ReportExportWorker {
	return jobs.NewReportExportWorker(exports, reports.MonthlyReport, reports.DailyLog)
}

// provideRiverWorkers registers every worker this process runs.
func provideRiverWorkers(
	holidaySyncWorker *jobs.HolidaySyncWorker,
	attendanceAutoCloseWorker *jobs.AttendanceAutoCloseWorker,
	reportExportWorker *jobs.ReportExportWorker,
) *river.Workers {
	workers := jobs.Workers()
	river.AddWorker(workers, holidaySyncWorker)
	river.AddWorker(workers, attendanceAutoCloseWorker)
	river.AddWorker(workers, reportExportWorker)
	return workers
}

// providePeriodicJobs schedules holiday sync (daily, current year,
// UpsertSynced's "manual edits win" guard makes re-runs safe, RunOnStart so
// a fresh deploy doesn't wait a day) and attendance auto-close (hourly —
// cheap no-op once a day's stragglers are closed, since the underlying
// UPDATE only ever touches rows still missing a checkout). Report export has
// no periodic schedule — it's only ever triggered on demand via
// ReportExportUsecase.RequestExport.
func providePeriodicJobs() []*river.PeriodicJob {
	return []*river.PeriodicJob{river.NewPeriodicJob(river.PeriodicInterval(24*time.Hour), func() (river.JobArgs, *river.InsertOpts) {
		return jobs.HolidaySyncArgs{Year: time.Now().Year()}, nil
	},
		&river.PeriodicJobOpts{RunOnStart: true},
	), river.NewPeriodicJob(river.PeriodicInterval(1*time.Hour), func() (river.JobArgs, *river.InsertOpts) {
		return jobs.AttendanceAutoCloseArgs{}, nil
	},
		&river.PeriodicJobOpts{RunOnStart: true},
	),
	}
}
